/* noema-lite language-course UI — GENERATED by tools/build.py from engine/lang/*.js. Do not edit. */
(function () {

/* ---- 00_base.js ---- */
/* noema-lite · language courses — the UI (docs/LANGUAGES.md §8). Built by tools/build.py into engine/langui.js.
   It runs instead of the subject engine when a language course is open; the runtime logic lives in engine/langcore.js. */
const N = window.NoemaLang;
const UI = { acc: null, id: null, C: null, L: null, lang: null, view: 'home', arg: null, prefs: {}, day: 0 };

/* ---------- tiny DOM helper ---------- */
function h(tag, attrs, ...kids) {
  const e = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs || {})) {
    if (v == null || v === false) continue;
    if (k === 'style' && typeof v === 'object') Object.assign(e.style, v);
    else if (k.startsWith('on')) e.addEventListener(k.slice(2), v);
    else if (k === 'html') e.innerHTML = v;
    else e.setAttribute(k, v === true ? '' : v);
  }
  for (const k of kids.flat(9)) if (k != null && k !== false) e.append(k instanceof Node ? k : document.createTextNode(String(k)));
  return e;
}
const $ = (s, r = document) => r.querySelector(s);
const shuffle = a => { const b = a.slice(); for (let i = b.length - 1; i > 0; i--) { const j = Math.random() * (i + 1) | 0; [b[i], b[j]] = [b[j], b[i]]; } return b; };
const uniq = a => [...new Set(a)];

/* ---------- languages: names, flags, scripts ---------- */
const LANG_INFO = {
  ar: { flag: '🇸🇦', name: 'Arabic', font: "'Noto Naskh Arabic'" }, he: { flag: '🇮🇱', name: 'Hebrew', font: "'Noto Sans Hebrew'" },
  zh: { flag: '🇨🇳', name: 'Chinese', font: "'Noto Sans SC'" }, de: { flag: '🇩🇪', name: 'German' }, el: { flag: '🇬🇷', name: 'Greek' },
  en: { flag: '🇬🇧', name: 'English' }, ru: { flag: '🇷🇺', name: 'Russian' }, tr: { flag: '🇹🇷', name: 'Turkish' }, hi: { flag: '🇮🇳', name: 'Hindi' },
  fr: { flag: '🇫🇷', name: 'French' }, es: { flag: '🇪🇸', name: 'Spanish' }, it: { flag: '🇮🇹', name: 'Italian' }, ja: { flag: '🇯🇵', name: 'Japanese' },
};
const info = code => ({ flag: '🏳️', name: code, ...(LANG_INFO[code] || {}), ...((UI.C?.data.course.flags || {})[code] ? { flag: UI.C.data.course.flags[code] } : {}) });
const LX = code => UI.C.lang[code];
const SUB_EMOJI = { root: '🥕', bulb: '🧅', stem: '🌿', leafy: '🥬', brassica: '🥦', fruitveg: '🍅', cucurbit: '🎃', legume: '🫛', flower: '🌸', sea: '🌊', pron: '👤', verb: '🏃', func: '🔤' };
const conceptEmoji = cid => SUB_EMOJI[UI.C.concepts[cid]?.subgroup] || '🔹';

/** A foreign word as the learner should see it: right font and direction; vowel marks on/off; transliteration or pinyin under it. */
function word(code, text, { lex = null, cls = '', sub = true } = {}) {
  const X = LX(code), marks = X.language.vowelMarks && UI.prefs.marks === false;
  const shown = marks ? N.stripMarks(code, text) : text;
  const e = h('span', { class: 'lx-w ' + cls, lang: code, dir: X.language.dir || 'ltr' }, shown);
  if (!sub || !lex) return e;
  const helper = code === 'zh' && UI.prefs.pinyin !== false && lex.pinyin && text === lex.lemma ? lex.pinyin.replace(/\s+/g, '')
    : X.language.vowelMarks && UI.prefs.translit !== false && lex.translit && text === lex.lemma ? lex.translit : null;
  return helper ? h('span', { class: 'lx-wbox' }, e, h('span', { class: 'lx-help', lang: code === 'zh' ? 'zh-Latn-pinyin' : 'und-Latn' }, helper)) : e;
}
/** What a word means, in the explanation language. */
function gloss(code, lid) {
  const x = LX(code).lex[lid], c = (x.senses || [])[0];
  return c ? UI.C.concepts[c]?.gloss || c : (x.role || '');
}
const STATE_LABEL = { locked: '🔒 locked', ready: '○ new', seen: '◔ seen', learning: '◑ learning', known_r: '◕ known (reading)', known_p: '● known', mastered: '★ mastered', absent: '— no word', unprepared: '⏳ not written yet', open: '○ open', known: '● known', skipped: '⤼ skipped' };

/* ---------- learner state: one storage key per (language, node) and per (language, function) ---------- */
const P = () => `noema1:${UI.acc}:s:lang:${UI.id}:`;
function loadLearner() {
  const kv = {}, p = P();
  for (let i = 0; i < localStorage.length; i++) {
    const k = localStorage.key(i);
    if (k && k.startsWith(p)) { try { kv[k.slice(p.length)] = JSON.parse(localStorage.getItem(k)); } catch (e) { } }
  }
  UI.prefs = kv.prefs || {};
  return N.fromKV(UI.C, kv);
}
let saveTimer = null;
function save(now = false) {
  clearTimeout(saveTimer);
  const go = () => {
    const kv = N.toKV(UI.C, UI.L); kv.prefs = UI.prefs;
    for (const [k, v] of Object.entries(kv)) {
      const key = P() + k, val = JSON.stringify(v);
      if (window.Noema?.kv) Noema.kv.set(key, val); else localStorage.setItem(key, val);   // Noema.kv marks the key for cloud sync
    }
  };
  if (now) go(); else saveTimer = setTimeout(go, 250);
}
const today = () => N.dayNumber();
const activeLangs = () => (UI.L.settings.languages || UI.C.languages).filter(c => UI.C.lang[c]);

/* ---- 10_shell.js ---- */
/* ---------- the shell: start, top bar, routes ---------- */
function start({ acc, id, data }) {
  UI.acc = acc; UI.id = id; UI.C = N.course(data); UI.L = loadLearner(); UI.day = today();
  UI.lang = UI.prefs.lang && UI.C.lang[UI.prefs.lang] ? UI.prefs.lang : activeLangs()[0];
  document.title = `${UI.C.data.course.title} · noema-lite`;
  document.documentElement.lang = UI.C.explainLang;
  const fonts = h('link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;600&family=Noto+Sans+Hebrew:wght@400;600&family=Noto+Sans+SC:wght@400;600&display=swap' });
  document.head.append(fonts);
  document.body.classList.add('lx');
  document.body.append(h('header', { class: 'topbar lx-top' }), h('main', { class: 'lx-main' }));
  addEventListener('hashchange', render);
  document.addEventListener('visibilitychange', () => { if (document.visibilityState === 'hidden') save(true); });
  render();
}
function go(hash) { if (location.hash === hash) render(); else location.hash = hash; }
function route() { const p = (location.hash || '#/').slice(2).split('/').map(decodeURIComponent); return { name: p[0] || 'home', arg: p[1] || null, arg2: p[2] || null }; }

function topbar() {
  const t = $('.lx-top'); t.innerHTML = '';
  const k = Object.fromEntries(activeLangs().map(c => [c, N.known(UI.C, UI.L, c)]));
  t.append(
    h('div', { class: 'brand', onclick: () => go('#/') }, h('div', { class: 'logo' }, '🌍'), h('span', { class: 'lx-title' }, UI.C.data.course.title)),
    h('span', { class: 'spacer' }),
    h('span', { class: 'chip lx-explain', title: 'Explanations, meanings and feedback are written in this language (chosen when the course was made)' }, '💬 ' + info(UI.C.explainLang).name),
    ...activeLangs().map(c => {
      const total = Object.keys(LX(c).lex).length, kn = Object.values(k[c].state).filter(s => ['known_r', 'known_p', 'mastered'].includes(s)).length;
      return h('button', { class: 'chip lx-flagchip' + (c === UI.lang ? ' on' : ''), title: `${info(c).name}: ${kn} of ${total} words known`, onclick: () => { UI.lang = c; UI.prefs.lang = c; save(); render(); } },
        h('span', { class: 'lx-flag' }, info(c).flag), c.toUpperCase(), h('span', { class: 'lx-ring', style: { '--p': total ? Math.round(kn / total * 100) : 0 } }));
    }),
    h('button', { class: 'iconbtn', title: 'Settings', onclick: () => go('#/settings') }, '⚙️'),
    h('button', { class: 'iconbtn', title: 'Choose another subject or course', onclick: () => window.Noema?.openSubjectPicker ? Noema.openSubjectPicker() : null }, '📚'));
}
const VIEWS = {};
function render() {
  const r = route(); UI.view = r.name;
  topbar();
  const m = $('.lx-main'); m.innerHTML = ''; window.scrollTo(0, 0);
  const v = h('div', { class: 'view lx-view' });
  m.append(v);
  (VIEWS[r.name] || VIEWS.home)(v, r);
}
/** A row of flag buttons for a card: one per course language, with the state of the concept in it. */
function flagRail(cid, current, onPick) {
  return h('div', { class: 'lx-rail', role: 'tablist', 'aria-label': 'Languages' }, ...UI.C.languages.map(c => {
    const st = cid ? N.conceptState(UI.C, UI.L, c, cid) : null;
    return h('button', { class: 'lx-railbtn' + (c === current ? ' on' : ''), role: 'tab', 'aria-selected': c === current ? 'true' : 'false', title: `${info(c).name} — ${STATE_LABEL[st] || ''}`, onclick: () => onPick(c) },
      h('span', { class: 'lx-flag' }, info(c).flag), h('span', { class: 'lx-dot s-' + (st || 'none') }));
  }));
}

/* ---------- home ---------- */
VIEWS.home = (v) => {
  const plan = N.planSession(UI.C, UI.L, { day: today(), minutes: UI.L.settings.minutes || 20 });
  const nRev = plan.steps.filter(s => s.kind === 'review').reduce((a, s) => a + s.items.length, 0);
  const learn = plan.steps.find(s => s.kind === 'learn');
  const nNew = learn ? learn.concepts.reduce((a, c) => a + c.langs.length, 0) : 0;
  v.append(h('div', { class: 'lx-hero' },
    h('h1', {}, UI.C.data.course.title),
    h('p', { class: 'lx-sub' }, `${UI.C.languages.map(c => info(c).flag + ' ' + info(c).name).join(' · ')} — explained in ${info(UI.C.explainLang).name}`),
    h('div', { class: 'row' },
      h('button', { class: 'btn primary lx-go', disabled: !(nRev || nNew), onclick: () => runSession(plan) }, nRev || nNew ? `▶ Today's session — ${nRev} review${nRev === 1 ? '' : 's'} · ${nNew} new` : '✅ Nothing due — come back tomorrow'),
      learn ? h('span', { class: 'tiny' }, `new words from “${UI.C.nodes[learn.node].title}”, the same ideas in every language`) : null)));
  v.append(h('h2', { class: 'lx-h2' }, '🗺️ The vocabulary map'), nodeList());
};
function nodeList() {
  const st = Object.fromEntries(UI.C.languages.map(c => [c, N.nodeStates(UI.C, UI.L, c)]));
  return h('div', { class: 'lx-nodes' }, ...UI.C.order.map(nid => {
    const n = UI.C.nodes[nid];
    return h('button', { class: 'lx-node', onclick: () => go('#/node/' + nid) },
      h('div', { class: 'lx-nodetitle' }, h('b', {}, n.title), h('span', { class: 'tiny' }, `${n.concepts.length} ideas` + (n.prereqs?.length ? ' · after ' + n.prereqs.map(p => UI.C.nodes[p].title.split(' — ')[0]).join(', ') : ''))),
      h('div', { class: 'lx-nodestates' }, ...UI.C.languages.map(c => h('span', { class: 'lx-ns ns-' + st[c][nid], title: `${info(c).name}: ${STATE_LABEL[st[c][nid]] || st[c][nid]}` }, info(c).flag, ' ', (STATE_LABEL[st[c][nid]] || st[c][nid])))));
  }));
}

/* ---- 20_cards.js ---- */
/* ---------- a node: its ideas, in the chosen language ---------- */
VIEWS.node = (v, r) => {
  const n = UI.C.nodes[r.arg]; if (!n) return VIEWS.home(v);
  const c = UI.lang, X = LX(c), k = N.known(UI.C, UI.L, c), ns = k.nodes[n.id];
  v.append(h('div', { class: 'lx-back' }, h('button', { class: 'btn ghost small', onclick: () => go('#/') }, '← Map')),
    h('h1', {}, n.title),
    h('div', { class: 'row' }, flagRail(null, c, x => { UI.lang = x; UI.prefs.lang = x; save(); render(); }),
      h('span', { class: 'lx-ns ns-' + ns }, info(c).flag, ' ', STATE_LABEL[ns] || ns)),
    h('div', { class: 'row lx-actions' },
      ['open', 'learning', 'known', 'mastered'].includes(ns) ? h('button', { class: 'btn primary small', onclick: () => runSession(N.planSession(UI.C, UI.L, { day: today(), minutes: 15, languages: [c] }), { only: n.id }) }, '▶ Learn / review this node') : null,
      n.kind === 'field' ? h('button', { class: 'btn small', onclick: () => go('#/field/' + encodeURIComponent(n.field) + '/' + n.tier) }, '🧺 Field map') : null,
      n.kind === 'field' && ['learning', 'known', 'mastered'].includes(ns) ? h('button', { class: 'btn small', onclick: () => go('#/recall/' + encodeURIComponent(n.field)) }, '⏱️ Name them all') : null),
    !X.prepared[n.id] ? h('p', { class: 'lx-note' }, `⏳ The ${info(c).name} words of this node are not written yet.`) : null);
  const grid = h('div', { class: 'lx-cgrid' });
  const ids = [...n.concepts.map(cid => ({ cid })), ...(X.byNode[n.id] || []).filter(id => !(X.lex[id].senses || []).length).map(id => ({ lex: id }))];
  for (const it of ids) grid.append(conceptTile(c, it, k));
  v.append(grid);
};
function conceptTile(c, { cid, lex }, k) {
  const X = LX(c), lids = cid ? (X.byConcept[cid] || []) : [lex], absent = cid && X.absent[cid];
  const st = cid ? N.conceptState(UI.C, UI.L, c, cid, k) : k.state[lex];
  const visible = !['locked', 'ready'].includes(st) || UI.prefs.peek;
  return h('button', { class: 'lx-tile s-' + st, onclick: () => go(cid ? '#/c/' + cid : '#/w/' + c + '/' + lex), title: STATE_LABEL[st] || '' },
    h('span', { class: 'lx-temoji' }, cid ? conceptEmoji(cid) : '🔤'),
    h('span', { class: 'lx-tword' }, absent ? h('i', { class: 'tiny' }, '— no word') : visible ? lids.map((id, i) => [i ? ' · ' : '', word(c, X.lex[id].lemma, { sub: false })]) : '?'),
    h('span', { class: 'lx-tgloss' }, cid ? UI.C.concepts[cid].gloss : gloss(c, lex)));
}

/* ---------- a concept: the flag card (one language at a time) + compare ---------- */
VIEWS.c = (v, r) => {
  const cid = r.arg, con = UI.C.concepts[cid]; if (!con) return VIEWS.home(v);
  const node = UI.C.nodes[UI.C.owner[cid]];
  const draw = () => {
    v.innerHTML = ''; topbar();
    v.append(h('div', { class: 'lx-back' }, h('button', { class: 'btn ghost small', onclick: () => history.length > 1 ? history.back() : go('#/node/' + node.id) }, '← ' + node.title)),
      h('div', { class: 'lx-cardhead' }, h('span', { class: 'lx-bigemoji' }, conceptEmoji(cid)), h('div', {}, h('h1', {}, con.gloss), h('div', { class: 'tiny' }, [node.title, con.wikidata ? 'Wikidata ' + con.wikidata : null].filter(Boolean).join(' · ')))),
      h('div', { class: 'row' }, flagRail(cid, UI.lang, x => { UI.lang = x; UI.prefs.lang = x; save(); draw(); }),
        h('button', { class: 'btn small' + (UI.prefs.compare ? ' primary' : ''), onclick: () => { UI.prefs.compare = !UI.prefs.compare; save(); draw(); } }, '⇄ Compare')));
    if (UI.prefs.compare) v.append(compareTable(cid));
    const X = LX(UI.lang), lids = X.byConcept[cid] || [];
    if (X.absent[cid]) v.append(h('div', { class: 'lx-absent' }, h('b', {}, `${info(UI.lang).flag} No ${info(UI.lang).name} word for this. `), X.absent[cid].reason, X.absent[cid].use ? h('div', {}, 'Instead: ', h('b', {}, X.absent[cid].use)) : null));
    else if (!X.prepared[node.id]) v.append(h('p', { class: 'lx-note' }, `⏳ Not written yet in ${info(UI.lang).name}.`));
    for (const lid of lids) v.append(wordCardView(UI.lang, lid));
  };
  draw();
};
VIEWS.w = (v, r) => { const c = r.arg, lid = r.arg2; if (!UI.C.lang[c]?.lex[lid]) return VIEWS.home(v); v.append(h('div', { class: 'lx-back' }, h('button', { class: 'btn ghost small', onclick: () => history.back() }, '← Back')), wordCardView(c, lid)); };

function compareTable(cid) {
  const rows = UI.C.languages.map(c => {
    const X = LX(c), lids = X.byConcept[cid] || [];
    const first = lids[0] && N.wordCard(UI.C, UI.L, c, lids[0]);
    return h('tr', {}, h('th', {}, info(c).flag + ' ' + info(c).name),
      h('td', {}, X.absent[cid] ? h('i', {}, '— ', X.absent[cid].use || 'no word') : lids.map((id, i) => [i ? h('br') : null, word(c, X.lex[id].lemma, { lex: X.lex[id] })])),
      h('td', { class: 'tiny' }, first ? first.parts.slice(0, 2).map(p => `${p[0]}: ${p[1]}`).join(' · ') : ''),
      h('td', {}, first?.examples[0] ? h('span', {}, word(c, first.examples[0].text, { sub: false }), h('div', { class: 'tiny' }, first.examples[0].tr)) : ''));
  });
  return h('div', { class: 'lx-compare' }, h('table', {}, h('tbody', {}, ...rows)));
}

/** Everything about one word (docs/LANGUAGES.md §4.6). */
function wordCardView(c, lid) {
  const card = N.wordCard(UI.C, UI.L, c, lid), X = LX(c), lx = X.lex[lid];
  const badge = (t, cls = '') => t ? h('span', { class: 'lx-badge ' + cls }, t) : null;
  const ex = e => h('div', { class: 'lx-ex' },
    h('div', { class: 'lx-extext' }, word(c, e.text, { sub: false })),
    e.py && UI.prefs.pinyin !== false ? h('div', { class: 'lx-help' }, e.py) : null,
    X.language.vowelMarks && UI.prefs.marks !== false ? h('div', { class: 'lx-plain', lang: c, dir: X.language.dir }, e.plain) : null,
    h('div', { class: 'lx-tr' }, e.tr),
    h('div', { class: 'lx-chips' }, badge('🎭 ' + [].concat(e.register).join(', '), 'reg'), badge('📍 ' + e.context, 'ctx'), e.senseDef ? badge('≈ ' + e.senseDef, 'sense') : null,
      e.unknown?.length ? badge('🆕 ' + e.unknown.length + ' new word' + (e.unknown.length > 1 ? 's' : ''), 'new') : null));
  const sec = {
    senses: items => h('ol', { class: 'lx-senses' }, ...items.map(s => h('li', {}, h('b', {}, s.def), ' ', badge([].concat(s.register || []).join(', '), 'reg'), s.domains ? badge(s.domains.join(', '), 'ctx') : null))),
    examples: items => h('div', {}, ...items.map(ex)),
    collocations: items => h('ul', { class: 'lx-list' }, ...items.map(x => h('li', {}, word(c, x.text, { sub: false }), ' — ', x.tr))),
    particleVerbs: items => h('ul', { class: 'lx-list' }, ...items.map(x => h('li', {}, word(c, x.text, { sub: false }), ' — ', x.tr))),
    phrases: items => h('ul', { class: 'lx-list' }, ...items.map(x => h('li', {}, word(c, x.text, { sub: false }), ' ', badge(x.kind, 'ctx'), x.register ? badge([].concat(x.register).join(', '), 'reg') : null,
      h('div', { class: 'tiny' }, '“' + x.tr + '” — ', h('b', {}, x.meaning), x.source ? ' (' + x.source + ')' : '')))),
    synonyms: groups => h('div', {}, ...Object.entries(groups).map(([reg, list]) => h('div', { class: 'lx-syngroup' }, badge(reg, 'reg'),
      h('ul', { class: 'lx-list' }, ...list.map(s => h('li', {}, word(c, s.word, { sub: false }), s.region ? badge('🗺️ ' + s.region, 'ctx') : null, ' — ', s.nuance)))))),
    antonyms: items => h('ul', { class: 'lx-list' }, ...items.map(x => h('li', {}, word(c, x.word, { sub: false }), x.note ? ' — ' + x.note : ''))),
    pitfalls: items => h('ul', { class: 'lx-list lx-warn' }, ...items.map(x => h('li', {}, x))),
    subtleties: items => h('ul', { class: 'lx-list' }, ...items.map(x => h('li', {}, x))),
    etymology: items => h('div', {}, ...items.map(x => h('p', {}, x.text, h('span', { class: 'tiny' }, ' — ' + x.src)))),
    funFacts: items => h('ul', { class: 'lx-list' }, ...items.map(x => h('li', {}, '💡 ', x))),
  };
  return h('article', { class: 'lx-card', lang: UI.C.explainLang },
    h('div', { class: 'lx-cardtop' },
      h('div', { class: 'lx-lemma' }, word(c, lx.lemma, { lex: lx })),
      h('div', { class: 'lx-meta' }, h('div', {}, h('b', {}, card.gloss)), h('div', { class: 'lx-chips' },
        badge(STATE_LABEL[card.state] || card.state, 'st s-' + card.state), badge(card.frequency, 'freq'), badge(card.status && card.status !== 'current' ? card.status : null, 'reg'),
        ...card.register.map(r => badge('🎭 ' + r, 'reg')), badge(card.connotation ? { positive: '🙂 positive', negative: '🙁 negative', neutral: '😐 neutral', mixed: '🤔 mixed' }[card.connotation] : null, 'ctx'),
        card.intensity ? badge('strength ' + '●'.repeat(card.intensity) + '○'.repeat(5 - card.intensity), 'ctx') : null))),
    card.parts.length ? h('dl', { class: 'lx-parts' }, ...card.parts.flatMap(([k, val]) => [h('dt', {}, k), h('dd', {}, /[֐-ۿ一-鿿]/.test(val) ? word(c, val, { sub: false }) : val)])) : null,
    card.feeling ? h('p', { class: 'lx-feeling' }, '💭 ', card.feeling) : null,
    ...card.sections.map(s => h('details', { class: 'lx-sec', open: ['senses', 'examples', 'pitfalls'].includes(s.key) ? true : null },
      h('summary', {}, s.title, h('span', { class: 'tiny' }, ' ' + (Array.isArray(s.items) ? s.items.length : Object.values(s.items).flat().length))), sec[s.key](s.items))),
    card.synonymsNone ? h('p', { class: 'tiny' }, 'Synonyms: ', card.synonymsNone) : null,
    !card.hasProfile ? h('p', { class: 'tiny' }, 'A little word: ', gloss(c, lid)) : null);
}

/* ---- 30_vocab.js ---- */
/* ---------- the field map: the whole thematic field, every tier, grouped by subgroup ---------- */
VIEWS.field = (v, r) => {
  const fid = r.arg, tierPick = r.arg2 ? +r.arg2 : 0;
  const field = UI.C.data.fields.find(f => f.field === fid); if (!field) return VIEWS.home(v);
  const c = UI.lang, k = N.known(UI.C, UI.L, c);
  const all = field.concepts;
  v.append(h('div', { class: 'lx-back' }, h('button', { class: 'btn ghost small', onclick: () => go('#/') }, '← Map')),
    h('h1', {}, '🧺 ', field.title, h('span', { class: 'tiny' }, ` · ${all.length} in all`)),
    h('div', { class: 'row' }, flagRail(null, c, x => { UI.lang = x; UI.prefs.lang = x; save(); render(); }),
      h('div', { class: 'lx-seg' }, ...[0, 1, 2, 3].map(t => h('button', { class: tierPick === t ? 'on' : '', onclick: () => go(`#/field/${encodeURIComponent(fid)}/${t}`) }, t ? ['', 'common', 'less common', 'rare'][t] : 'all'))),
      h('label', { class: 'tiny lx-peek' }, h('input', { type: 'checkbox', checked: UI.prefs.peek ? true : null, onchange: e => { UI.prefs.peek = e.target.checked; save(); render(); } }), ' show words not learned yet')));
  for (const sg of field.subgroups || [{ id: null, title: '' }]) {
    const items = all.filter(x => (sg.id == null || x.subgroup === sg.id) && (!tierPick || x.tier === tierPick)).sort((a, b) => a.tier - b.tier || a.rank - b.rank);
    if (!items.length) continue;
    v.append(h('h3', { class: 'lx-h3' }, (SUB_EMOJI[sg.id] || '') + ' ' + sg.title, h('span', { class: 'tiny' }, ' ' + items.length)),
      h('div', { class: 'lx-cgrid' }, ...items.map((x, i) => {
        const t = conceptTile(c, { cid: x.id }, k);
        if (i && items[i - 1].tier !== x.tier) t.classList.add('lx-tierbreak');
        t.dataset.tier = x.tier; return t;
      })));
  }
};

/* ---------- ⏱️ name them all: free recall of a whole field ---------- */
function fold(code, s) {
  let t = N.stripMarks(code, N.nfc(String(s))).toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g, '').replace(/[\s'’\-·]+/g, '');
  return t.replace(/ß/g, 'ss');
}
/** Every way the learner may type a word: any form, without vowel marks, full spelling, transliteration, pinyin with or without tones. */
function spellings(code, x) {
  const out = new Set([x.lemma, ...Object.values(x.forms || {}), ...Object.values(x.plene || {}), ...(x.alts || [])].map(s => fold(code, s)));
  if (x.translit) out.add(fold(code, x.translit));
  if (x.pinyin) { out.add(fold(code, x.pinyin)); out.add(fold(code, N.pinyinMarksToNumbers(x.pinyin).replace(/\d/g, ''))); }
  if (x.trad) out.add(fold(code, x.trad));
  return out;
}
VIEWS.recall = (v, r) => {
  const fid = r.arg, field = UI.C.data.fields.find(f => f.field === fid); if (!field) return VIEWS.home(v);
  const c = UI.lang, X = LX(c), k = N.known(UI.C, UI.L, c);
  const words = Object.values(X.lex).filter(x => (x.senses || []).some(s => UI.C.concepts[s]?.field === fid));
  const found = new Map(); let left = 180, timer = null;
  const input = h('input', { class: 'noema-input lx-recallin', lang: c, dir: X.language.dir, placeholder: `Type a ${info(c).name} word and press Enter…`, autocomplete: 'off', autocapitalize: 'off', spellcheck: 'false' });
  const clock = h('b', { class: 'lx-clock' }, '3:00'), list = h('div', { class: 'lx-found' }), msg = h('div', { class: 'tiny' });
  const finish = () => {
    clearInterval(timer); input.disabled = true;
    const taught = words.filter(x => k.R.has(x.id)), got = [...found.keys()];
    const bonus = got.filter(id => !k.R.has(id));
    v.append(h('div', { class: 'lx-result' }, h('h2', {}, `${got.length} of ${words.length} ${field.title.toLowerCase()} in ${info(c).name}`),
      h('p', {}, `Of the ${taught.length} you have learned you named ${got.filter(id => k.R.has(id)).length}.`, bonus.length ? ` And ${bonus.length} you have not been taught yet — well done!` : ''),
      h('details', {}, h('summary', {}, 'The ones you did not name'), h('div', { class: 'lx-cgrid' }, ...words.filter(x => !found.has(x.id)).map(x => conceptTile(c, { cid: x.senses[0] }, k))))));
    // naming a learned word counts as a correct production review
    for (const id of got) if (k.R.has(id)) N.review(UI.C, UI.L, c, id, 'p', 'good', today());
    save(true);
  };
  input.addEventListener('keydown', e => {
    if (e.key !== 'Enter') return;
    const t = fold(c, input.value); input.value = '';
    if (!t) return;
    if (!timer) timer = setInterval(() => { left--; clock.textContent = `${left / 60 | 0}:${String(left % 60).padStart(2, '0')}`; if (left <= 0) finish(); }, 1000);
    const hit = words.find(x => !found.has(x.id) && spellings(c, x).has(t));
    if (hit) { found.set(hit.id, true); list.prepend(h('span', { class: 'lx-hit' }, word(c, hit.lemma, { sub: false }), ' ', h('span', { class: 'tiny' }, gloss(c, hit.id)))); msg.textContent = `✓ ${found.size}`; }
    else msg.textContent = words.some(x => spellings(c, x).has(t)) ? 'already named' : 'not in this field (or a spelling I do not know)';
  });
  v.append(h('div', { class: 'lx-back' }, h('button', { class: 'btn ghost small', onclick: () => history.back() }, '← Back')),
    h('h1', {}, `⏱️ Name all the ${field.title.toLowerCase()} you can — ${info(c).flag} ${info(c).name}`),
    h('p', { class: 'tiny' }, 'Any form counts; without vowel marks, in transliteration or pinyin (tones optional) too. The clock starts with your first word.'),
    h('div', { class: 'row' }, input, clock, h('button', { class: 'btn small', onclick: finish }, 'Done')), msg, list);
  setTimeout(() => input.focus(), 50);
};

/* ---------- ⚙️ settings ---------- */
VIEWS.settings = (v) => {
  const S = UI.L.settings;
  const langBox = h('div', { class: 'lx-setrow' }, ...UI.C.languages.map(c => h('label', { class: 'lx-check' },
    h('input', { type: 'checkbox', checked: activeLangs().includes(c) ? true : null, onchange: e => { const s = new Set(activeLangs()); e.target.checked ? s.add(c) : s.delete(c); if (!s.size) { e.target.checked = true; return; } S.languages = UI.C.languages.filter(x => s.has(x)); save(); } }),
    ' ', info(c).flag, ' ', info(c).name,
    h('select', { 'aria-label': `How far to go in ${info(c).name}`, onchange: e => { S.depth = { ...(S.depth || {}), [c]: +e.target.value }; save(); } },
      ...[[1, 'common words only'], [2, 'common + less common'], [3, 'everything, the rare ones too']].map(([d, t]) => h('option', { value: d, selected: (S.depth?.[c] ?? 3) === d ? true : null }, t))))));
  const num = (label, key, min, max, def) => h('label', { class: 'lx-setrow' }, label, ' ', h('input', { type: 'number', min, max, value: S[key] || def, onchange: e => { S[key] = Math.max(min, Math.min(max, +e.target.value || def)); save(); } }));
  const tog = (label, key) => h('label', { class: 'lx-check' }, h('input', { type: 'checkbox', checked: UI.prefs[key] !== false ? true : null, onchange: e => { UI.prefs[key] = e.target.checked; save(); } }), ' ', label);
  v.append(h('div', { class: 'lx-back' }, h('button', { class: 'btn ghost small', onclick: () => go('#/') }, '← Map')), h('h1', {}, '⚙️ Settings'),
    h('h3', { class: 'lx-h3' }, 'Languages you study now'), langBox,
    h('h3', { class: 'lx-h3' }, 'Sessions'), num('New ideas per session', 'batch', 3, 30, 12), num('Minutes per session', 'minutes', 5, 120, UI.C.data.course.defaults?.dailyMinutes || 20),
    h('h3', { class: 'lx-h3' }, 'Reading help'), tog('Vowel marks in Arabic and Hebrew', 'marks'), tog('Transliteration under Arabic and Hebrew words', 'translit'), tog('Pinyin under Chinese words', 'pinyin'),
    h('p', { class: 'tiny' }, `Explanations are in ${info(UI.C.explainLang).name}: the language chosen when the course was made.`));
};

/* ---- 40_ex.js ---- */
/* ---------- exercises of the vocabulary lane (docs/LANGUAGES.md §6.2) ---------- */
const clusters = s => { try { return [...new Intl.Segmenter(undefined, { granularity: 'grapheme' }).segment(s)].map(x => x.segment); } catch (e) { return [...s]; } };

/** Other words of the same language to compare with: same subgroup first, then the same field, then anything. */
function neighbours(c, lid, n, pred = () => true) {
  const X = LX(c), me = X.lex[lid], cid = (me.senses || [])[0], con = UI.C.concepts[cid] || {};
  const pool = Object.values(X.lex).filter(x => x.id !== lid && pred(x) && !(x.senses || []).some(s => (me.senses || []).includes(s)));
  const score = x => { const k = UI.C.concepts[(x.senses || [])[0]] || {}; return (k.subgroup && k.subgroup === con.subgroup ? 0 : k.field && k.field === con.field ? 1 : 2) + (x.pos === me.pos ? 0 : 3) + Math.random(); };
  return pool.sort((a, b) => score(a) - score(b)).slice(0, n);
}
function feedback(box, ok, c, lid, extra) {
  box.append(h('div', { class: 'lx-fb ' + (ok ? 'ok' : 'bad') }, ok ? '✅ ' : '❌ ', word(c, LX(c).lex[lid].lemma, { lex: LX(c).lex[lid] }), ' — ', gloss(c, lid), extra ? h('div', { class: 'tiny' }, extra) : null));
}
function options(list, onPick) {
  const wrap = h('div', { class: 'lx-opts' });
  list.forEach((o, i) => wrap.append(h('button', { class: 'lx-opt', 'data-k': i + 1, onclick: e => { if (wrap.dataset.done) return; wrap.dataset.done = 1; onPick(o, e.currentTarget, wrap); } }, h('span', { class: 'lx-k' }, i + 1), o.label)));
  return wrap;
}
function markOpts(wrap, isRight) { [...wrap.children].forEach((b, i) => { if (isRight(i)) b.classList.add('right'); }); }

/** recognize: the word → its meaning (recognition track). */
function exRecognize(c, lid, done) {
  const X = LX(c), me = X.lex[lid], box = h('div', { class: 'lx-ex lx-exrec' });
  const right = gloss(c, lid);
  const opts = shuffle([{ label: right, ok: true }, ...uniq(neighbours(c, lid, 8).map(x => gloss(c, x.id))).filter(g => g && g !== right).slice(0, 3).map(g => ({ label: g }))]);
  box.append(h('div', { class: 'lx-q' }, 'What does it mean?'), h('div', { class: 'lx-prompt' }, word(c, me.lemma, { lex: me })),
    options(opts, (o, b, wrap) => { b.classList.add(o.ok ? 'right' : 'wrong'); if (!o.ok) markOpts(wrap, i => opts[i].ok); feedback(box, !!o.ok, c, lid); done(!!o.ok); }));
  return box;
}
/** produce: the meaning → the word. Spelled with letter tiles (any script) — or chosen, for long words. */
function exProduce(c, lid, done) {
  const X = LX(c), me = X.lex[lid], box = h('div', { class: 'lx-ex lx-exprod' });
  const cid = (me.senses || [])[0];
  box.append(h('div', { class: 'lx-q' }, `In ${info(c).name}?`), h('div', { class: 'lx-prompt lx-meaning' }, cid ? conceptEmoji(cid) + ' ' : '', gloss(c, lid)));
  const parts = clusters(me.lemma).filter(t => t.trim());   // multi-word words: the spaces are not tiles
  const afterWord = ok => extraCheck(c, lid, box, ok2 => { feedback(box, ok && ok2, c, lid); done(ok && ok2); }, ok);
  if (parts.length > 14) {
    const opts = shuffle([{ label: word(c, me.lemma, { sub: false }), ok: true }, ...neighbours(c, lid, 3).map(x => ({ label: word(c, x.lemma, { sub: false }) }))]);
    box.append(options(opts, (o, b, wrap) => { b.classList.add(o.ok ? 'right' : 'wrong'); if (!o.ok) markOpts(wrap, i => opts[i].ok); afterWord(!!o.ok); }));
    return box;
  }
  const others = neighbours(c, lid, 6).flatMap(x => clusters(x.lemma)).filter(x => x.trim() && !parts.includes(x));
  const tiles = shuffle([...parts.map((t, i) => ({ t, i })), ...shuffle(uniq(others)).slice(0, Math.min(4, Math.max(2, parts.length >> 1))).map(t => ({ t }))]);
  const built = [], slot = h('div', { class: 'lx-slot', lang: c, dir: X.language.dir }), pool = h('div', { class: 'lx-tiles', lang: c, dir: X.language.dir });
  const drawSlot = () => { slot.textContent = built.map(b => b.t).join('') || '…'; };
  let over = false;
  const check = () => {
    over = true; const ok = N.nfc(built.map(b => b.t).join('')) === N.nfc(me.lemma.replace(/\s+/g, ''));
    slot.classList.add(ok ? 'right' : 'wrong'); [...pool.children].forEach(b => b.disabled = true); afterWord(ok);
  };
  tiles.forEach(tile => pool.append(h('button', { class: 'lx-tile1', onclick: e => { if (over || e.currentTarget.disabled) return; built.push(tile); e.currentTarget.disabled = true; e.currentTarget.dataset.used = built.length; drawSlot(); if (built.length === parts.length) check(); } }, tile.t === ' ' ? '␣' : tile.t)));
  const undo = h('button', { class: 'btn small ghost', onclick: () => { if (over || !built.length) return; built.pop(); const b = [...pool.children].find(x => +x.dataset.used === built.length + 1); if (b) { b.disabled = false; delete b.dataset.used; } drawSlot(); } }, '⌫');
  const giveUp = h('button', { class: 'btn small ghost', onclick: () => { if (!over) { over = true; slot.classList.add('wrong'); afterWord(false); } } }, 'Show me');
  // Latin script: typing is allowed too
  const typed = X.language.script === 'Latn' ? h('input', { class: 'noema-input lx-typein', placeholder: 'or type it…', autocapitalize: 'off', spellcheck: 'false', onkeydown: e => {
    if (e.key !== 'Enter' || over) return; over = true; const ok = N.nfc(e.target.value.trim()) === N.nfc(me.lemma) || (X.language.capitalizeFirst && N.nfc(e.target.value.trim()).toLowerCase() === N.nfc(me.lemma).toLowerCase() && me.pos !== 'NOUN');
    slot.textContent = e.target.value.trim(); slot.classList.add(ok ? 'right' : 'wrong'); afterWord(ok); } }) : null;
  drawSlot();
  box.append(slot, pool, h('div', { class: 'row' }, undo, giveUp, typed));
  return box;
}
/** After the word itself: what must be learned with it — the German article, the Chinese measure word. */
function extraCheck(c, lid, box, done, wordOk) {
  const me = LX(c).lex[lid];
  if (c === 'de' && me.pos === 'NOUN' && me.gender && me.class !== 'plt') {
    const right = { MASC: 'der', FEM: 'die', NEUT: 'das' }[me.gender], opts = ['der', 'die', 'das'].map(a => ({ label: a, ok: a === right }));
    box.append(h('div', { class: 'lx-q' }, wordOk ? 'And its article?' : 'Its article?'), options(opts, (o, b, wrap) => { b.classList.add(o.ok ? 'right' : 'wrong'); if (!o.ok) markOpts(wrap, i => opts[i].ok); done(!!o.ok); }));
    return;
  }
  if (c === 'zh' && me.pos === 'NOUN' && me.measure?.length) {
    const clf = Object.values(LX(c).lex).filter(x => x.pos === 'CLF').map(x => x.lemma);
    const right = me.measure[0], wrongs = shuffle(clf.filter(m => !me.measure.includes(m))).slice(0, 3);
    const opts = shuffle([{ label: '一' + right, ok: true }, ...wrongs.map(m => ({ label: '一' + m }))]);
    box.append(h('div', { class: 'lx-q' }, 'Which measure word? (one …)'), options(opts.map(o => ({ ...o, label: word(c, o.label, { sub: false }) })), (o, b, wrap) => { b.classList.add(o.ok ? 'right' : 'wrong'); if (!o.ok) markOpts(wrap, i => opts[i].ok); done(!!o.ok); }));
    return;
  }
  done(true);
}
/** The first meeting with a word: everything needed to recognize it, briefly. */
function exIntro(c, lid, done) {
  const X = LX(c), me = X.lex[lid], card = N.wordCard(UI.C, UI.L, c, lid);
  const e1 = card.examples[0];
  const box = h('div', { class: 'lx-ex lx-intro' },
    h('div', { class: 'lx-q' }, `New in ${info(c).flag} ${info(c).name}`),
    h('div', { class: 'lx-prompt' }, word(c, me.lemma, { lex: me })),
    h('div', { class: 'lx-meaning' }, (me.senses?.[0] ? conceptEmoji(me.senses[0]) + ' ' : '') + card.gloss),
    card.parts.length ? h('dl', { class: 'lx-parts' }, ...card.parts.slice(0, 4).flatMap(([k, val]) => [h('dt', {}, k), h('dd', {}, /[֐-ۿ一-鿿]/.test(val) ? word(c, val, { sub: false }) : val)])) : null,
    e1 ? h('div', { class: 'lx-ex1' }, word(c, e1.text, { sub: false }), h('div', { class: 'tiny' }, e1.tr)) : null,
    card.sections.find(s => s.key === 'pitfalls') ? h('div', { class: 'lx-warn tiny' }, '⚠️ ', card.sections.find(s => s.key === 'pitfalls').items[0]) : null,
    h('div', { class: 'row' }, h('button', { class: 'btn primary lx-next', onclick: () => done(true) }, 'Got it →')));
  return box;
}

/* ---- 50_session.js ---- */
/* ---------- the session: reviews, then new ideas learned in every language one after the other (§7.5) ---------- */
/** A batch of one node only (“Learn / review this node”). */
function nodePlan(nid, langs) {
  const plan = N.planSession(UI.C, UI.L, { day: today(), minutes: 15, languages: langs });
  const reviews = plan.steps.filter(s => s.kind === 'review').flatMap(s => s.items).filter(it => LX(it.lang).lex[it.lex].node === nid);
  const k = Object.fromEntries(langs.map(c => [c, N.known(UI.C, UI.L, c)]));
  const concepts = [];
  for (const cid of UI.C.nodes[nid].concepts) {
    const e = langs.flatMap(c => (LX(c).byConcept[cid] || []).filter(id => k[c].state[id] === 'ready').slice(0, 1).map(id => ({ lang: c, lex: id })));
    if (e.length && concepts.length < (UI.L.settings.batch || 12)) concepts.push({ concept: cid, langs: e });
  }
  for (const c of langs) for (const id of LX(c).byNode[nid] || []) if (!(LX(c).lex[id].senses || []).length && k[c].state[id] === 'ready' && concepts.length < (UI.L.settings.batch || 12)) concepts.push({ concept: id, langs: [{ lang: c, lex: id }] });
  return { steps: [...(reviews.length ? [{ kind: 'review', items: reviews }] : []), ...(concepts.length ? [{ kind: 'learn', node: nid, concepts }] : [])] };
}
function runSession(plan, { only = null } = {}) {
  if (only) plan = nodePlan(only, [UI.lang]);
  const queue = [];
  for (const s of plan.steps) {
    if (s.kind === 'review') for (const it of s.items) queue.push({ kind: it.track === 'r' ? 'rec' : 'prod', lang: it.lang, lex: it.lex, review: true });
    if (s.kind === 'learn') for (const cn of s.concepts) {
      for (const e of cn.langs) queue.push({ kind: 'intro', ...e });
      for (const e of cn.langs) queue.push({ kind: 'rec', ...e });
      for (const e of cn.langs) queue.push({ kind: 'prod', ...e });
    }
  }
  if (!queue.length) { go('#/'); return; }
  const total = queue.length, stats = { right: 0, wrong: 0, introduced: 0 }, retried = new Set();
  const before = Object.fromEntries(activeLangs().map(c => [c, N.nodeStates(UI.C, UI.L, c)]));
  const m = $('.lx-main'); const bar = h('div', { class: 'lx-progress' }, h('i')), stage = h('div', { class: 'lx-stage' });
  m.innerHTML = ''; m.append(h('div', { class: 'view lx-view lx-session' }, h('div', { class: 'row' }, h('button', { class: 'btn ghost small', onclick: () => { save(true); go('#/'); render(); } }, '✕ Stop'), bar), stage));
  let i = 0;
  const next = () => {
    bar.firstChild.style.width = Math.round(i / (total + retried.size) * 100) + '%';
    const a = queue.shift();
    if (!a) return finish();
    i++; stage.innerHTML = '';
    const day = today();
    const done = ok => {
      if (a.kind === 'intro') { N.introduce(UI.C, UI.L, a.lang, a.lex, day); stats.introduced++; save(); return next(); }
      N.review(UI.C, UI.L, a.lang, a.lex, a.kind === 'rec' ? 'r' : 'p', ok ? 'good' : 'again', day); save();
      ok ? stats.right++ : stats.wrong++;
      const key = a.kind + a.lang + a.lex;
      if (!ok && !retried.has(key)) { retried.add(key); queue.splice(Math.min(3, queue.length), 0, { ...a, retry: true }); }   // once more, a little later
      const btn = h('button', { class: 'btn primary lx-next' }, 'Next →'); btn.onclick = next;
      stage.append(h('div', { class: 'row lx-nextrow' }, btn)); setTimeout(() => btn.focus(), 30);
    };
    const ex = a.kind === 'intro' ? exIntro(a.lang, a.lex, done) : a.kind === 'rec' ? exRecognize(a.lang, a.lex, done) : exProduce(a.lang, a.lex, done);
    Object.assign(ex.dataset, { kind: a.kind, lang: a.lang, lex: a.lex });   // for tests and styling
    stage.append(h('div', { class: 'tiny lx-which' }, info(a.lang).flag, ' ', info(a.lang).name, a.review ? ' · review' : '', a.retry ? ' · once more' : ''), ex);
  };
  const finish = () => {
    save(true); bar.firstChild.style.width = '100%'; stage.innerHTML = '';
    const opened = [];
    for (const c of activeLangs()) { const now = N.nodeStates(UI.C, UI.L, c); for (const nid of UI.C.order) if (before[c][nid] !== now[nid] && ['open', 'known', 'mastered'].includes(now[nid])) opened.push(`${info(c).flag} ${UI.C.nodes[nid].title}: ${STATE_LABEL[now[nid]]}`); }
    stage.append(h('div', { class: 'lx-result' }, h('h2', {}, '🎉 Session done'),
      h('p', {}, `${stats.introduced} new · ${stats.right} right · ${stats.wrong} to practise again`),
      opened.length ? h('ul', {}, ...opened.map(t => h('li', {}, t))) : null,
      h('button', { class: 'btn primary', onclick: () => go('#/') }, 'Back to the map')));
  };
  document.onkeydown = e => {
    if (!$('.lx-session')) { document.onkeydown = null; return; }
    if (/^[1-4]$/.test(e.key) && !/input/i.test(document.activeElement?.tagName)) { const b = [...stage.querySelectorAll('.lx-opts:not([data-done]) .lx-opt')][+e.key - 1]; b?.click(); }
  };
  next();
}
window.NoemaLangUI = { start, UI };

})();
