# (id, gloss, subgroup, tier, enwiki title)
C = [
# ---- tier 1: everyday vegetables
('veg.carrot','carrot','root',1,'Carrot'), ('veg.potato','potato','root',1,'Potato'), ('veg.onion','onion','bulb',1,'Onion'),
('veg.garlic','garlic','bulb',1,'Garlic'), ('veg.tomato','tomato','fruitveg',1,'Tomato'), ('veg.cucumber','cucumber','cucurbit',1,'Cucumber'),
('veg.lettuce','lettuce','leafy',1,'Lettuce'), ('veg.cabbage','cabbage','brassica',1,'Cabbage'), ('veg.bellpepper','bell pepper, sweet pepper','fruitveg',1,'Bell pepper'),
('veg.eggplant','eggplant, aubergine','fruitveg',1,'Eggplant'), ('veg.zucchini','zucchini, courgette','cucurbit',1,'Zucchini'), ('veg.pumpkin','pumpkin','cucurbit',1,'Pumpkin'),
('veg.spinach','spinach','leafy',1,'Spinach'), ('veg.broccoli','broccoli','brassica',1,'Broccoli'), ('veg.cauliflower','cauliflower','brassica',1,'Cauliflower'),
('veg.pea','pea','legume',1,'Pea'), ('veg.greenbean','green bean','legume',1,'Green bean'), ('veg.corn','sweet corn, maize','fruitveg',1,'Sweet corn'),
('veg.celery','celery','stem',1,'Celery'), ('veg.leek','leek','bulb',1,'Leek'), ('veg.radish','radish','root',1,'Radish'),
('veg.beetroot','beetroot, beet','root',1,'Beetroot'), ('veg.sweetpotato','sweet potato','root',1,'Sweet potato'), ('veg.chili','chili pepper','fruitveg',1,'Chili pepper'),
('veg.springonion','spring onion, scallion','bulb',1,'Scallion'),
# ---- tier 2: known to most people, less everyday
('veg.artichoke','artichoke','flower',2,'Artichoke'), ('veg.asparagus','asparagus','stem',2,'Asparagus'), ('veg.okra','okra','fruitveg',2,'Okra'),
('veg.kale','kale','brassica',2,'Kale'), ('veg.brusselssprout','Brussels sprout','brassica',2,'Brussels sprout'), ('veg.redcabbage','red cabbage','brassica',2,'Red cabbage'),
('veg.napacabbage','Napa cabbage, Chinese cabbage','brassica',2,'Napa cabbage'), ('veg.bokchoy','bok choy, pak choi','brassica',2,'Bok choy'), ('veg.kohlrabi','kohlrabi','brassica',2,'Kohlrabi'),
('veg.fennel','fennel (bulb)','stem',2,'Florence fennel'), ('veg.turnip','turnip','root',2,'Turnip'), ('veg.parsnip','parsnip','root',2,'Parsnip'),
('veg.celeriac','celeriac, celery root','root',2,'Celeriac'), ('veg.horseradish','horseradish','root',2,'Horseradish'), ('veg.ginger','ginger','root',2,'Ginger'),
('veg.shallot','shallot','bulb',2,'Shallot'), ('veg.redonion','red onion','bulb',2,'Red onion'), ('veg.arugula','arugula, rocket','leafy',2,'Arugula'),
('veg.watercress','watercress','leafy',2,'Watercress'), ('veg.chard','Swiss chard, chard','leafy',2,'Chard'), ('veg.endive','endive','leafy',2,'Endive'),
('veg.chicory','chicory, Belgian endive','leafy',2,'Chicory'), ('veg.radicchio','radicchio','leafy',2,'Radicchio'), ('veg.lambslettuce',"lamb's lettuce, corn salad",'leafy',2,'Valerianella locusta'),
('veg.cress','garden cress','leafy',2,'Lepidium sativum'), ('veg.icebergl','iceberg lettuce','leafy',2,'Iceberg lettuce'), ('veg.romaine','romaine lettuce, cos','leafy',2,'Romaine lettuce'),
('veg.broadbean','broad bean, fava bean','legume',2,'Vicia faba'), ('veg.snowpea','snow pea, mangetout','legume',2,'Snow pea'), ('veg.runnerbean','runner bean','legume',2,'Phaseolus coccineus'),
('veg.beansprout','bean sprouts','legume',2,'Bean sprout'), ('veg.cherrytomato','cherry tomato','fruitveg',2,'Cherry tomato'), ('veg.jalapeno','jalapeño','fruitveg',2,'Jalapeño'),
('veg.butternut','butternut squash','cucurbit',2,'Butternut squash'), ('veg.chayote','chayote','cucurbit',2,'Chayote'), ('veg.bittermelon','bitter melon, bitter gourd','cucurbit',2,'Momordica charantia'),
('veg.wintermelon','winter melon, ash gourd','cucurbit',2,'Benincasa hispida'), ('veg.luffa','luffa, sponge gourd','cucurbit',2,'Luffa'), ('veg.bottlegourd','bottle gourd, calabash','cucurbit',2,'Calabash'),
('veg.cassava','cassava, manioc','root',2,'Cassava'), ('veg.taro','taro','root',2,'Taro'), ('veg.yam','yam','root',2,'Yam (vegetable)'),
('veg.jerusalemartichoke','Jerusalem artichoke, sunchoke','root',2,'Jerusalem artichoke'), ('veg.rutabaga','rutabaga, swede','root',2,'Rutabaga'), ('veg.daikon','daikon, white radish','root',2,'Daikon'),
('veg.lotusroot','lotus root','stem',2,'Lotus root'), ('veg.bambooshoot','bamboo shoot','stem',2,'Bamboo shoot'), ('veg.waterspinach','water spinach, morning glory greens','leafy',2,'Ipomoea aquatica'),
('veg.purslane','purslane','leafy',2,'Portulaca oleracea'), ('veg.mustardgreens','mustard greens','leafy',2,'Brassica juncea'), ('veg.collards','collard greens','brassica',2,'Collard (plant)'),
('veg.molokhia','jute mallow, molokhia','leafy',2,'Corchorus olitorius'), ('veg.garlicchives','garlic chives, Chinese chives','bulb',2,'Allium tuberosum'), ('veg.wildgarlic','wild garlic, ramsons','bulb',2,'Allium ursinum'),
('veg.nettle','stinging nettle (greens)','leafy',2,'Urtica dioica'), ('veg.dandelion','dandelion greens','leafy',2,'Taraxacum officinale'), ('veg.sorrel','sorrel','leafy',2,'Common sorrel'),
('veg.blacksalsify','black salsify, scorzonera','root',2,'Scorzonera hispanica'),
# ---- tier 3: the rare tail
('veg.salsify','salsify','root',3,'Tragopogon porrifolius'), ('veg.rootparsley','root parsley, Hamburg parsley','root',3,'Petroselinum crispum'), ('veg.skirret','skirret','root',3,'Sium sisarum'),
('veg.burdock','burdock root, gobo','root',3,'Arctium lappa'), ('veg.wasabi','wasabi','root',3,'Wasabi'), ('veg.galangal','galangal','root',3,'Alpinia galanga'),
('veg.turmeric','turmeric (fresh root)','root',3,'Turmeric'), ('veg.jicama','jícama','root',3,'Pachyrhizus erosus'), ('veg.yacon','yacón','root',3,'Yacón'),
('veg.oca','oca','root',3,'Oxalis tuberosa'), ('veg.ulluco','ulluco','root',3,'Ullucus tuberosus'), ('veg.mashua','mashua','root',3,'Tropaeolum tuberosum'),
('veg.arracacha','arracacha','root',3,'Arracacia xanthorrhiza'), ('veg.tigernut','tiger nut','root',3,'Cyperus esculentus'), ('veg.waterchestnut','water chestnut','stem',3,'Eleocharis dulcis'),
('veg.watercaltrop','water caltrop','stem',3,'Water caltrop'), ('veg.purpleyam','purple yam, ube','root',3,'Dioscorea alata'), ('veg.chineseartichoke','Chinese artichoke, crosne','root',3,'Stachys affinis'),
('veg.elephantyam','elephant foot yam','root',3,'Amorphophallus paeoniifolius'), ('veg.konjac','konjac','root',3,'Konjac'),
('veg.malabarspinach','Malabar spinach','leafy',3,'Basella alba'), ('veg.nzspinach','New Zealand spinach','leafy',3,'Tetragonia tetragonioides'), ('veg.amaranth','amaranth greens','leafy',3,'Amaranthus dubius'),
('veg.orache','orache','leafy',3,'Atriplex hortensis'), ('veg.fathen','fat hen, lamb\'s quarters','leafy',3,'Chenopodium album'), ('veg.goodkinghenry','Good King Henry','leafy',3,'Blitum bonus-henricus'),
('veg.borage','borage','leafy',3,'Borage'), ('veg.minerslettuce',"miner's lettuce, winter purslane",'leafy',3,'Claytonia perfoliata'), ('veg.landcress','land cress','leafy',3,'Barbarea verna'),
('veg.mizuna','mizuna','brassica',3,'Mizuna'), ('veg.komatsuna','komatsuna','brassica',3,'Komatsuna'), ('veg.tatsoi','tatsoi','brassica',3,'Tatsoi'),
('veg.kailan','Chinese broccoli, kai-lan','brassica',3,'Gai lan'), ('veg.rapini','rapini, broccoli rabe','brassica',3,'Rapini'), ('veg.romanesco','Romanesco broccoli','brassica',3,'Romanesco broccoli'),
('veg.seakale','sea kale','brassica',3,'Crambe maritima'), ('veg.savoy','Savoy cabbage','brassica',3,'Savoy cabbage'), ('veg.pointedcabbage','pointed cabbage','brassica',3,'Pointed cabbage'),
('veg.celtuce','celtuce, stem lettuce','stem',3,'Celtuce'), ('veg.cardoon','cardoon','stem',3,'Cardoon'), ('veg.heartofpalm','heart of palm','stem',3,'Heart of palm'),
('veg.nopal','nopal, prickly-pear pad','stem',3,'Nopal'), ('veg.fiddlehead','fiddlehead fern','stem',3,'Fiddlehead fern'), ('veg.samphire','samphire, sea fennel','stem',3,'Crithmum'),
('veg.glasswort','glasswort, sea asparagus','stem',3,'Salicornia'), ('veg.rhubarb','rhubarb','stem',3,'Rhubarb'),
('veg.elephantgarlic','elephant garlic','bulb',3,'Elephant garlic'), ('veg.pearlonion','pearl onion','bulb',3,'Pearl onion'), ('veg.kurrat','kurrat, Egyptian leek','bulb',3,'Allium ampeloprasum'),
('veg.ramps','ramps, wild leek','bulb',3,'Allium tricoccum'), ('veg.treeonion','tree onion, walking onion','bulb',3,'Tree onion'), ('veg.welshonion','Welsh onion, bunching onion','bulb',3,'Allium fistulosum'),
('veg.kabocha','kabocha','cucurbit',3,'Kabocha'), ('veg.spaghettisquash','spaghetti squash','cucurbit',3,'Spaghetti squash'), ('veg.pattypan','pattypan squash','cucurbit',3,'Pattypan squash'),
('veg.acorns','acorn squash','cucurbit',3,'Acorn squash'), ('veg.snakegourd','snake gourd','cucurbit',3,'Trichosanthes cucumerina'), ('veg.ridgedgourd','ridged gourd','cucurbit',3,'Luffa acutangula'),
('veg.ivygourd','ivy gourd, tindora','cucurbit',3,'Coccinia grandis'), ('veg.pointedgourd','pointed gourd, parwal','cucurbit',3,'Trichosanthes dioica'), ('veg.tinda','tinda, Indian round gourd','cucurbit',3,'Praecitrullus fistulosus'),
('veg.armeniancucumber','Armenian cucumber','cucurbit',3,'Armenian cucumber'), ('veg.cucamelon','cucamelon, mouse melon','cucurbit',3,'Melothria scabra'), ('veg.kiwano','kiwano, horned melon','cucurbit',3,'Cucumis metuliferus'),
('veg.gherkin','gherkin','cucurbit',3,'Gherkin'),
('veg.tomatillo','tomatillo','fruitveg',3,'Tomatillo'), ('veg.habanero','habanero','fruitveg',3,'Habanero'), ('veg.cayenne','cayenne pepper','fruitveg',3,'Cayenne pepper'),
('veg.padron','Padrón pepper','fruitveg',3,'Padrón pepper'), ('veg.babycorn','baby corn','fruitveg',3,'Baby corn'),
('veg.yardlongbean','yardlong bean','legume',3,'Yardlong bean'), ('veg.wingedbean','winged bean','legume',3,'Psophocarpus tetragonolobus'), ('veg.limabean','lima bean','legume',3,'Lima bean'),
('veg.edamame','edamame','legume',3,'Edamame'), ('veg.sugarsnap','sugar snap pea','legume',3,'Snap pea'), ('veg.guar','guar bean, cluster bean','legume',3,'Guar'),
('veg.drumstick','drumstick (moringa pod)','legume',3,'Moringa oleifera'),
('veg.capers','caper','flower',3,'Caper'), ('veg.bananaflower','banana flower','flower',3,'Banana flower'), ('veg.zucchiniflower','zucchini flower','flower',3,'Squash blossom'),
('veg.nori','nori','sea',3,'Nori'), ('veg.wakame','wakame','sea',3,'Wakame'), ('veg.kombu','kombu','sea',3,'Kombu'),
('veg.hijiki','hijiki','sea',3,'Hijiki'), ('veg.dulse','dulse','sea',3,'Palmaria palmata'), ('veg.sealettuce','sea lettuce','sea',3,'Sea lettuce'),
('veg.seagrapes','sea grapes','sea',3,'Caulerpa lentillifera'),
]
