#!/usr/bin/env python3
"""noema-lite build tool (stdlib only).

  python3 tools/build.py                 # validate + build engine, every subject pack and the registry
  python3 tools/build.py site            # + dist/site/  (what the website serves: no PDFs, no private packs, no backups)
  python3 tools/build.py bundle [--subjects a,b] [--with-local-config]
                                         # + dist/noema-lite.html  (one self-contained file, e.g. for phone/offline)
  python3 tools/build.py --no-validate   # skip validation (faster)
"""
import os, sys, glob, json, subprocess, tempfile, shutil
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from noema_lib import ROOT, LIB, ACC, rj, wj, wt, now_iso, subject_dirs, load_subject, load_media, content_hash

ENGINE = os.path.join(ROOT, 'engine')
args = sys.argv[1:]
VALIDATE = '--no-validate' not in args

def build_engine():
    js = ''.join(f'\n/* ---- {os.path.basename(f)} ---- */\n' + open(f, encoding='utf-8').read() for f in sorted(glob.glob(os.path.join(ENGINE, 'src', '*.js'))))
    css = ''.join(f'\n/* ---- {os.path.basename(f)} ---- */\n' + open(f, encoding='utf-8').read() for f in sorted(glob.glob(os.path.join(ENGINE, 'src', '*.css'))))
    wt(os.path.join(ENGINE, 'engine.js'), '/* noema-lite engine — GENERATED by tools/build.py from engine/src/*.js. Do not edit. */\n' + js)
    wt(os.path.join(ENGINE, 'engine.css'), '/* noema-lite engine styles — GENERATED from engine/src/*.css. Do not edit. */\n' + css)
    print(f'engine: {len(js)//1024} KB js, {len(css)//1024} KB css')

def validate(chapters, label, media=None, min_visual=0):
    if not VALIDATE: return True
    ok = True
    with tempfile.TemporaryDirectory() as td:
        mp = os.path.join(td, '_media.json'); wj(mp, {k: {'w': v['w'], 'h': v['h'], 'regions': v.get('regions')} for k, v in (media or {}).items()})
        for c in chapters:
            p = os.path.join(td, c['id'] + '.json'); wj(p, c)
            r = subprocess.run([sys.executable, os.path.join(ROOT, 'tools', 'validate.py'), p, '--media', mp, '--min-visual', str(min_visual)], capture_output=True, text=True)
            if r.returncode != 0:
                ok = False; print(f'  ✗ {label}/{c["id"]}:\n' + '\n'.join('    ' + l for l in r.stdout.splitlines() if l.startswith('ERROR')))
    return ok

def build_packs():
    metas = []; failed = []
    for sdir, owner in subject_dirs():
        meta, sources, chapters, report = load_subject(sdir)
        media, mrep = load_media(sdir)
        for m in mrep:
            if m.startswith('WARN'): print('  ' + m)
        per_pic = int((meta.get('authoring') or {}).get('minExercisesPerPicture', 0))
        if per_pic:   # docs/VISUAL.md §5: every picture carries several exercises
            from collections import Counter
            used = Counter(e.get('media') for c in chapters for e in c['exercises'] if e['type'].startswith('img_'))
            for m in media:
                if used[m] < per_pic: mrep.append(f'ERROR media {m}: used by {used[m]} exercise(s); every picture needs >= {per_pic} (authoring.minExercisesPerPicture)')
        errs = [r for r in report + mrep if r.startswith('ERROR')]
        if errs: print('\n'.join(errs)); failed.append(meta['id']); continue
        if not validate(chapters, meta['id'], media, int((meta.get('authoring') or {}).get('minVisualPerChapter', 0))): failed.append(meta['id']); continue
        meta = dict(meta); meta['owner'] = owner
        counts = {'chapters': len(chapters), 'sections': sum(len(c['sections']) for c in chapters), 'exercises': sum(len(c['exercises']) for c in chapters),
                  'playbooks': sum(len(c['debug']) for c in chapters), 'flashcards': sum(len(c['flashcards']) for c in chapters)}
        counts['visual'] = sum(1 for c in chapters for e in c['exercises'] if e['type'].startswith('img_')); counts['media'] = len(media)
        pack = {'format': 'noema-pack', 'v': 1, 'subject': meta, 'sources': sources, 'chapters': chapters, 'media': media, 'counts': counts, 'builtAt': now_iso()}
        pack['version'] = content_hash({'s': meta, 'src': sources, 'c': chapters, 'm': {k: v['sha'] for k, v in media.items()}, 'mm': {k: {x: y for x, y in v.items() if x != 'data'} for k, v in media.items()}})
        try:   # unchanged content → keep the previous build time so git sees no change
            prev = rj(os.path.join(sdir, 'pack.json'))
            if prev.get('version') == pack['version']: pack['builtAt'] = prev.get('builtAt', pack['builtAt'])
        except Exception: pass
        body = json.dumps(pack, ensure_ascii=False, separators=(',', ':'))
        wt(os.path.join(sdir, 'pack.json'), body)
        wt(os.path.join(sdir, 'pack.js'), f'/* GENERATED subject pack: {meta["id"]} — do not edit; edit chapters/*.json and run tools/build.py */\n(window.NOEMA_PACKS = window.NOEMA_PACKS || {{}})[{json.dumps(meta["id"])}] = ' + body.replace('</', '<\\/') + ';\n')
        rel = os.path.relpath(os.path.join(sdir, 'pack.js'), ROOT).replace(os.sep, '/')
        metas.append(dict({k: meta.get(k) for k in ('id', 'title', 'appTitle', 'emoji', 'group', 'description', 'language', 'features', 'owner')}, path=rel, counts=counts, version=pack['version']))
        print(f'pack: {meta["id"]:<20} {"(private:" + owner + ")" if owner else "":<18} {counts["chapters"]} ch · {counts["sections"]} sec · {counts["exercises"]} ex ({counts["visual"]} visual) · {counts["media"]} img · {len(body)//1024} KB')
    return metas, failed

def build_registry(metas, public=False):
    groups = rj(os.path.join(LIB, 'groups.json'), {'groups': []})['groups']
    accounts = []
    if not public:
        for f in sorted(glob.glob(os.path.join(ACC, '*', 'account.json'))):
            a = rj(f); accounts.append({k: a.get(k) for k in ('id', 'name', 'emoji', 'learner', 'subjects')})
    subs = [m for m in metas if not (public and m.get('owner'))]
    reg = {'format': 'noema-registry', 'v': 1, 'builtAt': now_iso(), 'groups': groups, 'subjects': subs, 'accounts': accounts}
    return '/* GENERATED by tools/build.py — subject & profile registry */\nwindow.NOEMA_REGISTRY = ' + json.dumps(reg, ensure_ascii=False, indent=1).replace('</', '<\\/') + ';\n'

def build_site(metas):
    out = os.path.join(ROOT, 'dist', 'site')
    if os.path.exists(out): shutil.rmtree(out)
    os.makedirs(out)
    shutil.copy(os.path.join(ROOT, 'config.js'), out)
    # the website never has a config.local.js → drop its <script> tag (avoids a 404 + MIME error in the console)
    html = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
    html = '\n'.join(l for l in html.split('\n') if 'config.local.js' not in l)
    wt(os.path.join(out, 'index.html'), html)
    os.makedirs(os.path.join(out, 'engine'))
    for f in ('engine.js', 'engine.css', 'loader.js', 'convos.js', 'cloud.js'): shutil.copy(os.path.join(ENGINE, f), os.path.join(out, 'engine', f))
    shutil.copytree(os.path.join(ENGINE, 'vendor'), os.path.join(out, 'engine', 'vendor'))
    for m in metas:
        if m.get('owner'): continue
        dst = os.path.join(out, m['path']); os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy(os.path.join(ROOT, m['path']), dst)
    wt(os.path.join(out, 'library', 'registry.js'), build_registry(metas, public=True))
    wt(os.path.join(out, '_headers'), '/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n/engine/*\n  Cache-Control: public, max-age=300\n/library/*\n  Cache-Control: public, max-age=300\n')
    print('site →', os.path.relpath(out, ROOT))

def build_bundle(metas):
    sel = None
    if '--subjects' in args: sel = set(args[args.index('--subjects') + 1].split(','))
    rd = lambda p: open(os.path.join(ROOT, p), encoding='utf-8').read()
    esc = lambda s: s.replace('</script', '<\\/script')
    packs = ''.join(f'<script>{esc(rd(m["path"]))}</script>\n' for m in metas if (not sel or m['id'] in sel))
    reg_metas = [dict(m, path=None) for m in metas if (not sel or m['id'] in sel)]
    local = ''
    if '--with-local-config' in args and os.path.exists(os.path.join(ROOT, 'config.local.js')): local = f'<script>{esc(rd("config.local.js"))}</script>'
    css = rd('engine/engine.css')
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>noema-lite</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>◆</text></svg>">
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>{css}</style></head>
<body><div id="noema-splash"><div class="logo">◆</div></div>
<script>{esc(rd("config.js"))}</script>{local}
<script>window.NOEMA_BUNDLE = true;</script>
<script>{esc(build_registry(reg_metas))}</script>
{packs}<script>{esc(rd("engine/vendor/marked.umd.js"))}</script>
<script>{esc(rd("engine/vendor/purify.min.js"))}</script>
<script>{esc(rd("engine/convos.js"))}</script>
<script>{esc(rd("engine/cloud.js"))}</script>
<script type="text/plain" id="noema-engine-src">{esc(rd("engine/engine.js"))}</script>
<script>{esc(rd("engine/loader.js"))}</script>
</body></html>'''
    out = os.path.join(ROOT, 'dist', 'noema-lite.html'); wt(out, html)
    print(f'bundle → dist/noema-lite.html ({len(html)/1e6:.1f} MB, {len(reg_metas)} subjects{", with local config" if local else ""})')

if __name__ == '__main__':
    build_engine()
    metas, failed = build_packs()
    wt(os.path.join(LIB, 'registry.js'), build_registry(metas))
    print(f'registry: {len(metas)} subjects')
    if 'site' in args: build_site(metas)
    if 'bundle' in args: build_bundle(metas)
    if failed: print('FAILED:', ', '.join(failed)); sys.exit(1)
