#!/usr/bin/env python3
"""noema-lite build tool (stdlib only).

  python3 tools/build.py                 # validate + build engine, every subject pack and the registry
  python3 tools/build.py site            # + dist/site/  (what the website serves: no PDFs, no private packs, no backups)
  python3 tools/build.py skill           # + dist/noema-pack-builder.zip  (the Claude skill users add to their own Claude)
  python3 tools/build.py bundle [--subjects a,b] [--with-local-config]
                                         # + dist/noema-lite.html  (one self-contained file, e.g. for phone/offline)
  python3 tools/build.py --no-validate   # skip validation (faster)
"""
import os, sys, glob, json, subprocess, tempfile, shutil, re, zipfile
for _s in (sys.stdout, sys.stderr):   # UTF-8 output on Windows / macOS / Linux alike
    try: _s.reconfigure(encoding='utf-8', errors='replace')
    except Exception: pass
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from noema_lib import ROOT, LIB, ACC, rj, wj, wt, now_iso, subject_dirs, load_subject, load_media, content_hash

ENGINE = os.path.join(ROOT, 'engine')
args = sys.argv[1:]
VALIDATE = '--no-validate' not in args

def build_engine():
    js = ''.join(f'\n/* ---- {os.path.basename(f)} ---- */\n' + open(f, encoding='utf-8').read() for f in sorted(glob.glob(os.path.join(ENGINE, 'src', '*.js'))))
    css = ''.join(f'\n/* ---- {os.path.basename(f)} ---- */\n' + open(f, encoding='utf-8').read() for f in sorted(glob.glob(os.path.join(ENGINE, 'src', '*.css'))))
    wt(os.path.join(ENGINE, 'engine.js'), '/* noema-lite engine — GENERATED by tools/build.py from engine/src/*.js. Do not edit. */\n' + js)
    wt(os.path.join(ENGINE, 'engine.css'), '/* noema-lite engine styles — GENERATED from engine/src/*.css. Do not edit. */\n' + css)
    # the content contract for packs generated in the browser (engine/packgen.js)
    rd = lambda q: open(os.path.join(ROOT, q), encoding='utf-8').read()
    wt(os.path.join(ENGINE, 'authoring.js'), '/* GENERATED by tools/build.py from tools/CONTENT_SPEC.md + docs/VISUAL.md — do not edit */\nwindow.NOEMA_AUTHORING = '
       + json.dumps({'content': rd('tools/CONTENT_SPEC.md'), 'visual': rd('docs/VISUAL.md')}, ensure_ascii=False) + ';\n')
    print(f'engine: {len(js)//1024} KB js, {len(css)//1024} KB css')
    # the language courses' UI (docs/LANGUAGES.md §8): loaded instead of engine.js when a language course is open
    ljs = ''.join(f'\n/* ---- {os.path.basename(f)} ---- */\n' + open(f, encoding='utf-8').read() for f in sorted(glob.glob(os.path.join(ENGINE, 'lang', '*.js'))))
    lcss = ''.join(open(f, encoding='utf-8').read() for f in sorted(glob.glob(os.path.join(ENGINE, 'lang', '*.css'))))
    if ljs:
        wt(os.path.join(ENGINE, 'langui.js'), '/* noema-lite language-course UI — GENERATED by tools/build.py from engine/lang/*.js. Do not edit. */\n(function () {\n' + ljs + '\n})();\n')
        wt(os.path.join(ENGINE, 'langui.css'), '/* GENERATED from engine/lang/*.css. Do not edit. */\n' + lcss)

def validate(chapters, label, media=None, min_visual=0):
    if not VALIDATE: return True
    ok = True
    with tempfile.TemporaryDirectory() as td:
        mp = os.path.join(td, '_media.json'); wj(mp, {k: {'w': v['w'], 'h': v['h'], 'regions': v.get('regions')} for k, v in (media or {}).items()})
        for c in chapters:
            p = os.path.join(td, c['id'] + '.json'); wj(p, c)
            r = subprocess.run([sys.executable, os.path.join(ROOT, 'tools', 'validate.py'), p, '--media', mp, '--min-visual', str(min_visual)], capture_output=True, text=True)
            if r.returncode != 0:
                ok = False; print(f'  ✗ {label}/{c["id"]}:\n' + '\n'.join('    ' + l for l in r.stdout.splitlines() if l.startswith('ERROR')))
    return ok

def build_packs():
    metas = []; failed = []
    for sdir, owner in subject_dirs():
        meta, sources, chapters, report = load_subject(sdir)
        media, mrep = load_media(sdir)
        for m in mrep:
            if m.startswith('WARN'): print('  ' + m)
        per_pic = int((meta.get('authoring') or {}).get('minExercisesPerPicture', 0))
        if per_pic:   # docs/VISUAL.md §5: every picture carries several exercises
            from collections import Counter
            used = Counter(e.get('media') for c in chapters for e in c['exercises'] if e['type'].startswith('img_'))
            for m in media:
                if used[m] < per_pic: mrep.append(f'ERROR media {m}: used by {used[m]} exercise(s); every picture needs >= {per_pic} (authoring.minExercisesPerPicture)')
        errs = [r for r in report + mrep if r.startswith('ERROR')]
        if errs: print('\n'.join(errs)); failed.append(meta['id']); continue
        if not validate(chapters, meta['id'], media, int((meta.get('authoring') or {}).get('minVisualPerChapter', 0))): failed.append(meta['id']); continue
        meta = dict(meta); meta['owner'] = owner
        counts = {'chapters': len(chapters), 'sections': sum(len(c['sections']) for c in chapters), 'exercises': sum(len(c['exercises']) for c in chapters),
                  'playbooks': sum(len(c['debug']) for c in chapters), 'flashcards': sum(len(c['flashcards']) for c in chapters)}
        counts['visual'] = sum(1 for c in chapters for e in c['exercises'] if e['type'].startswith('img_')); counts['media'] = len(media)
        pack = {'format': 'noema-pack', 'v': 1, 'subject': meta, 'sources': sources, 'chapters': chapters, 'media': media, 'counts': counts, 'builtAt': now_iso()}
        pack['version'] = content_hash({'s': meta, 'src': sources, 'c': chapters, 'm': {k: v.get('sha') or v.get('url') for k, v in media.items()}, 'mm': {k: {x: y for x, y in v.items() if x != 'data'} for k, v in media.items()}})
        try:   # unchanged content → keep the previous build time so git sees no change
            prev = rj(os.path.join(sdir, 'pack.json'))
            if prev.get('version') == pack['version']: pack['builtAt'] = prev.get('builtAt', pack['builtAt'])
        except Exception: pass
        body = json.dumps(pack, ensure_ascii=False, separators=(',', ':'))
        wt(os.path.join(sdir, 'pack.json'), body)
        wt(os.path.join(sdir, 'pack.js'), f'/* GENERATED subject pack: {meta["id"]} — do not edit; edit chapters/*.json and run tools/build.py */\n(window.NOEMA_PACKS = window.NOEMA_PACKS || {{}})[{json.dumps(meta["id"])}] = ' + body.replace('</', '<\\/') + ';\n')
        rel = os.path.relpath(os.path.join(sdir, 'pack.js'), ROOT).replace(os.sep, '/')
        info = {'chapters': [{'num': c.get('num'), 'title': c['title'], 'emoji': c.get('emoji', ''), 'sections': len(c['sections']), 'exercises': len(c['exercises'])} for c in chapters],
                'sources': [{'title': x.get('title', ''), 'subtitle': x.get('subtitle', ''), 'pages': x.get('pages', ''), 'url': x.get('url', '') if str(x.get('url', '')).startswith('http') else ''} for x in (sources or {}).get('sources', [])]}
        metas.append(dict({k: meta.get(k) for k in ('id', 'title', 'appTitle', 'emoji', 'group', 'description', 'language', 'features', 'owner')}, path=rel, counts=dict(counts, pictures=len(media)), version=pack['version'], **info))
        print(f'pack: {meta["id"]:<20} {"(private:" + owner + ")" if owner else "":<18} {counts["chapters"]} ch · {counts["sections"]} sec · {counts["exercises"]} ex ({counts["visual"]} visual) · {counts["media"]} img · {len(body)//1024} KB')
    return metas, failed

def build_registry(metas, public=False):
    groups = rj(os.path.join(LIB, 'groups.json'), {'groups': []})['groups']
    accounts = []
    if not public:
        for f in sorted(glob.glob(os.path.join(ACC, '*', 'account.json'))):
            a = rj(f); accounts.append({k: a.get(k) for k in ('id', 'name', 'emoji', 'learner', 'subjects')})
    subs = [m for m in metas if not (public and m.get('owner'))]
    reg = {'format': 'noema-registry', 'v': 1, 'builtAt': now_iso(), 'groups': groups, 'subjects': subs, 'accounts': accounts}
    if LANG_METAS: reg['languages'] = LANG_METAS   # language courses (docs/LANGUAGES.md); absent when there are none
    return '/* GENERATED by tools/build.py — subject & profile registry */\nwindow.NOEMA_REGISTRY = ' + json.dumps(reg, ensure_ascii=False, indent=1).replace('</', '<\\/') + ';\n'

LANGS = os.path.join(LIB, 'languages')
LANG_METAS = []
def build_lang_courses():
    """Every language course in library/languages → course.pack.js (+ .json) and its registry entry (docs/LANGUAGES.md §4.1)."""
    out, failed = [], []
    if not os.path.isdir(LANGS): return out, failed
    sys.path.insert(0, os.path.join(ROOT, 'tools'))
    from validate_lang import validate as vlang
    for d in sorted(os.listdir(LANGS)):
        root = os.path.join(LANGS, d)
        if not os.path.exists(os.path.join(root, 'course.json')): continue
        if VALIDATE:
            v = vlang(root, None, strict=False)
            if v.errors: print(f'  ✗ language course {d}: {len(v.errors)} problem(s), e.g. {v.errors[0]}'); failed.append(d); continue
        J = lambda rel: rj(os.path.join(root, rel)) if os.path.exists(os.path.join(root, rel)) else None
        ls = lambda rel: sorted(f for f in os.listdir(os.path.join(root, rel)) if f.endswith('.json')) if os.path.isdir(os.path.join(root, rel)) else []
        course = J('course.json'); nodes = J('core/nodes.json')['nodes']
        data = {'course': course, 'typology': J('core/typology.json'), 'fields': [J('core/fields/' + f) for f in ls('core/fields')], 'nodes': nodes,
                'functions': [J('core/functions/' + f) for f in ls('core/functions')], 'frames': (J('core/frames.json') or {}).get('frames', []), 'langs': {}}
        for code in course['languages']:
            b = f'lang/{code}/'
            data['langs'][code] = {'language': J(b + 'language.json'), 'lexicon': {n['id']: J(f'{b}lexicon/{n["id"]}.json') for n in nodes if J(f'{b}lexicon/{n["id"]}.json')},
                                   'grammar': {f['id']: J(f'{b}grammar/{f["id"]}.json') for f in data['functions'] if J(f'{b}grammar/{f["id"]}.json')},
                                   'bank': [s for f in ls(b + 'bank') for s in J(b + 'bank/' + f).get('sentences', [])]}
        # the word profiles (half of the course) go into a second file that the app loads after the course has opened
        profiles = {}
        for L in data['langs'].values():
            for lx in L['lexicon'].values():
                for x in lx.get('lexemes', []):
                    if 'profile' in x: profiles[x['id']] = x.pop('profile')
        pbody = json.dumps(profiles, ensure_ascii=False, separators=(',', ':'))
        wt(os.path.join(root, 'course.profiles.js'), f'/* GENERATED word profiles of the language course {course["id"]} — do not edit */\n(window.NOEMA_LANGPROFILES = window.NOEMA_LANGPROFILES || {{}})[{json.dumps(course["id"])}] = ' + pbody.replace('</', '<\\/') + ';\n')
        body = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
        wt(os.path.join(root, 'course.pack.js'), f'/* GENERATED language course: {course["id"]} — do not edit; edit the JSON files and run tools/build.py */\n(window.NOEMA_LANGPACKS = window.NOEMA_LANGPACKS || {{}})[{json.dumps(course["id"])}] = ' + body.replace('</', '<\\/') + ';\n')
        words = {c: sum(len(v['lexemes']) for v in data['langs'][c]['lexicon'].values()) for c in course['languages']}
        out.append({'id': course['id'], 'title': course['title'], 'emoji': course.get('emoji', '🌍'), 'languages': course['languages'], 'explainLang': course.get('explainLang', 'en'),
                    'path': os.path.relpath(os.path.join(root, 'course.pack.js'), ROOT).replace(os.sep, '/'),
                    'profiles': os.path.relpath(os.path.join(root, 'course.profiles.js'), ROOT).replace(os.sep, '/'), 'words': words})
        print(f'language course: {course["id"]} · ' + ' · '.join(f'{c} {n} words' for c, n in words.items()) + f' · {len(body)//1024} KB + profiles {len(pbody)//1024} KB')
    return out, failed

def build_site(metas):
    out = os.path.join(ROOT, 'dist', 'site')
    if os.path.exists(out): shutil.rmtree(out)
    os.makedirs(out)
    shutil.copy(os.path.join(ROOT, 'config.js'), out)
    # the website never has a config.local.js → drop its <script> tag (avoids a 404 + MIME error in the console)
    html = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
    html = '\n'.join(l for l in html.split('\n') if 'config.local.js' not in l)
    wt(os.path.join(out, 'index.html'), html)
    os.makedirs(os.path.join(out, 'engine'))
    for f in ('langcore.js', 'langui.js', 'langui.css'):
        if os.path.exists(os.path.join(ENGINE, f)): shutil.copy(os.path.join(ENGINE, f), os.path.join(out, 'engine', f))
    for m in LANG_METAS:
        for k in ('path', 'profiles'):
            if not m.get(k): continue
            dst = os.path.join(out, m[k]); os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy(os.path.join(ROOT, m[k]), dst)
    for f in ('engine.js', 'engine.css', 'loader.js', 'convos.js', 'cloud.js', 'claude.js', 'packcheck.js', 'llm.js', 'curriculum.js', 'curjobs.js', 'imglib.js', 'curimport.js', 'packgen.js', 'curmap.js', 'authoring.js', 'srcfiles.js', 'viewer.js'): shutil.copy(os.path.join(ENGINE, f), os.path.join(out, 'engine', f))
    shutil.copytree(os.path.join(ENGINE, 'vendor'), os.path.join(out, 'engine', 'vendor'))
    for m in metas:
        if m.get('owner'): continue
        dst = os.path.join(out, m['path']); os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy(os.path.join(ROOT, m['path']), dst)
    for m in metas:   # the plain JSON too, so Claude (connector: noema_get_pack_url) can extend a library subject
        if not m.get('owner'): shutil.copy(os.path.join(ROOT, os.path.dirname(m['path']), 'pack.json'), os.path.join(out, os.path.dirname(m['path']), 'pack.json'))
    wt(os.path.join(out, 'library', 'registry.js'), build_registry(metas, public=True))
    # OAuth consent page for the Claude connector (Supabase → <site>/oauth/consent?authorization_id=…) → the app
    wt(os.path.join(out, 'oauth', 'consent', 'index.html'), '<!doctype html><meta charset="utf-8"><title>noema-lite</title><script>location.replace("/" + location.search + "#/connect-claude")</script>')
    build_skill(os.path.join(out, 'downloads', 'noema-pack-builder.zip'))
    build_mcp_function(metas, os.path.join(ROOT, 'dist', 'functions'))
    build_img_function(os.path.join(ROOT, 'dist', 'functions'))
    wt(os.path.join(out, '_headers'), '/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n/engine/*\n  Cache-Control: public, max-age=300\n/engine/vendor/pdfjs/*.mjs\n  Content-Type: text/javascript; charset=utf-8\n/engine/vendor/pdfjs/wasm/*.wasm\n  Content-Type: application/wasm\n/library/*\n  Cache-Control: public, max-age=300\n')
    print('site →', os.path.relpath(out, ROOT))

SKILL_TOOLS = ['noema_lib.py', 'validate.py', 'svgkit.py', 'extract_images.py', 'fetch_image.py', 'find_images.py']
def build_skill(out_zip):
    """The Claude skill (skill/noema-pack-builder) + the shared tools and the content contract, as one zip."""
    src = os.path.join(ROOT, 'skill', 'noema-pack-builder')
    os.makedirs(os.path.dirname(out_zip), exist_ok=True)
    with zipfile.ZipFile(out_zip, 'w', zipfile.ZIP_DEFLATED) as z:
        for f in sorted(glob.glob(os.path.join(src, '**', '*'), recursive=True)):
            if os.path.isfile(f) and '__pycache__' not in f: z.write(f, os.path.join('noema-pack-builder', os.path.relpath(f, src)))
        for t in SKILL_TOOLS: z.write(os.path.join(ROOT, 'tools', t), f'noema-pack-builder/scripts/{t}')
        z.write(os.path.join(ROOT, 'tools', 'CONTENT_SPEC.md'), 'noema-pack-builder/references/CONTENT_SPEC.md')
        z.write(os.path.join(ROOT, 'docs', 'VISUAL.md'), 'noema-pack-builder/references/VISUAL.md')
        if os.path.exists(os.path.join(ROOT, 'docs', 'LANGUAGES.md')): z.write(os.path.join(ROOT, 'docs', 'LANGUAGES.md'), 'noema-pack-builder/references/LANGUAGES.md')
    print('skill →', os.path.relpath(out_zip, ROOT))

def public_config():
    txt = open(os.path.join(ROOT, 'config.js'), encoding='utf-8').read()
    g = lambda k: (re.search(k + r"\s*:\s*'([^']*)'", txt) or [None, ''])[1]
    return {'siteUrl': g('siteUrl'), 'supabaseUrl': g('supabaseUrl'), 'supabaseKey': g('supabaseKey')}

# the app's own code the connector runs (pack checks; curriculum tasks, checks and how answers change a curriculum)
MCP_ENGINE = ['engine/packcheck.js', 'engine/llm.js', 'engine/curriculum.js', 'engine/curjobs.js', 'engine/imglib.js']
MCP_PRELUDE = 'globalThis.window = globalThis;\n'

def build_mcp_function(metas, out_dir):
    """dist/functions/mcp.mjs — the Claude connector (cloud/mcp/server.mjs + public config + the content contract)."""
    cfg = public_config()
    if not (cfg['siteUrl'] and cfg['supabaseUrl'] and cfg['supabaseKey']): print('mcp: skipped (config.js needs siteUrl, supabaseUrl, supabaseKey)'); return
    cfg['library'] = [{k: m.get(k) for k in ('id', 'title', 'counts', 'version')} for m in metas if not m.get('owner')]
    rd = lambda p: open(os.path.join(ROOT, p), encoding='utf-8').read()
    docs = {'workflow': rd('skill/noema-pack-builder/SKILL.md'), 'content': rd('tools/CONTENT_SPEC.md'), 'visual': rd('docs/VISUAL.md')}
    code = (f'/* GENERATED by tools/build.py from cloud/mcp/server.mjs — do not edit */\nconst CFG = {json.dumps(cfg, ensure_ascii=False)};\nconst DOCS = {json.dumps(docs, ensure_ascii=False)};\n'
            + MCP_PRELUDE + ''.join(rd(f) + '\n' for f in MCP_ENGINE) + rd('cloud/mcp/server.mjs') + '\nexport const config = { path: ["/mcp", "/.well-known/oauth-protected-resource", "/.well-known/oauth-protected-resource/mcp"] };\n')
    wt(os.path.join(out_dir, 'mcp.mjs'), code)
    print('mcp →', os.path.relpath(os.path.join(out_dir, 'mcp.mjs'), ROOT))

def build_img_function(out_dir):
    """dist/functions/img.mjs — /api/img, the picture fetcher for web pictures whose host blocks browsers (cloud/img/proxy.mjs)."""
    code = open(os.path.join(ROOT, 'cloud', 'img', 'proxy.mjs'), encoding='utf-8').read()
    lib = open(os.path.join(ROOT, 'engine', 'imglib.js'), encoding='utf-8').read()   # the picture library (resolve, page → picture, search)
    wt(os.path.join(out_dir, 'img.mjs'), '/* GENERATED by tools/build.py from engine/imglib.js + cloud/img/proxy.mjs — do not edit */\n' + lib + '\n' + code + '\nexport const config = { path: ["/api/img", "/api/file", "/api/imgsearch"] };\n')
    print('img →', os.path.relpath(os.path.join(out_dir, 'img.mjs'), ROOT))

def build_bundle(metas):
    sel = None
    if '--subjects' in args: sel = set(args[args.index('--subjects') + 1].split(','))
    rd = lambda p: open(os.path.join(ROOT, p), encoding='utf-8').read()
    esc = lambda s: s.replace('</script', '<\\/script')
    packs = ''.join(f'<script>{esc(rd(m["path"]))}</script>\n' for m in metas if (not sel or m['id'] in sel))
    reg_metas = [dict(m, path=None) for m in metas if (not sel or m['id'] in sel)]
    local = ''
    if '--with-local-config' in args and os.path.exists(os.path.join(ROOT, 'config.local.js')): local = f'<script>{esc(rd("config.local.js"))}</script>'
    css = rd('engine/engine.css')
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>noema-lite</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>◆</text></svg>">
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>{css}</style></head>
<body><div id="noema-splash"><div class="logo">◆</div></div>
<script>{esc(rd("config.js"))}</script>{local}
<script>window.NOEMA_BUNDLE = true;</script>
<script>{esc(build_registry(reg_metas))}</script>
{packs}<script>{esc(rd("engine/vendor/marked.umd.js"))}</script>
<script>{esc(rd("engine/vendor/purify.min.js"))}</script>
<script>{esc(rd("engine/convos.js"))}</script>
<script>{esc(rd("engine/cloud.js"))}</script>
<script>{esc(rd("engine/imglib.js"))}</script>
<script>{esc(rd("engine/claude.js"))}</script>
<script>{esc(rd("engine/srcfiles.js"))}</script>
<script>{esc(rd("engine/viewer.js"))}</script>
<script>{esc(rd("engine/packcheck.js"))}</script>
<script>{esc(rd("engine/llm.js"))}</script>
<script>{esc(rd("engine/packgen.js"))}</script>
<script>{esc(rd("engine/curriculum.js"))}</script>
<script>{esc(rd("engine/curjobs.js"))}</script>
<script>{esc(rd("engine/curimport.js"))}</script>
<script>{esc(rd("engine/curmap.js"))}</script>
<script>{esc(rd("engine/authoring.js"))}</script>
<script type="text/plain" id="noema-engine-src">{esc(rd("engine/engine.js"))}</script>
<script>{esc(rd("engine/loader.js"))}</script>
</body></html>'''
    out = os.path.join(ROOT, 'dist', 'noema-lite.html'); wt(out, html)
    print(f'bundle → dist/noema-lite.html ({len(html)/1e6:.1f} MB, {len(reg_metas)} subjects{", with local config" if local else ""})')

if __name__ == '__main__':
    build_engine()
    metas, failed = build_packs()
    LANG_METAS, lfailed = build_lang_courses(); failed += lfailed
    wt(os.path.join(LIB, 'registry.js'), build_registry(metas))
    print(f'registry: {len(metas)} subjects')
    if 'site' in args: build_site(metas)
    if 'skill' in args: build_skill(os.path.join(ROOT, 'dist', 'noema-pack-builder.zip'))
    if 'bundle' in args: build_bundle(metas)
    if failed: print('FAILED:', ', '.join(failed)); sys.exit(1)
