"""Shared helpers for noema-lite tools (stdlib only — runs anywhere Python 3.8+ runs)."""
import json, os, glob, hashlib, datetime

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
LIB = os.path.join(ROOT, 'library')
ACC = os.path.join(ROOT, 'accounts')

def rj(p, default=None):
    if default is not None and not os.path.exists(p): return default
    with open(p, encoding='utf-8') as f: return json.load(f)

def wj(p, obj, compact=False):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tmp = p + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as f:
        if compact: json.dump(obj, f, ensure_ascii=False, separators=(',', ':'))
        else: json.dump(obj, f, ensure_ascii=False, indent=1)
    os.replace(tmp, p)

def wt(p, text):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tmp = p + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as f: f.write(text)
    os.replace(tmp, p)

def now_iso(): return datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat()

def subject_dirs():
    """Yield (subject_dir, owner) for shared subjects and every account's private subjects."""
    for d in sorted(glob.glob(os.path.join(LIB, 'subjects', '*', 'subject.json'))):
        yield os.path.dirname(d), None
    for d in sorted(glob.glob(os.path.join(ACC, '*', 'packs', '*', 'subject.json'))):
        yield os.path.dirname(d), os.path.basename(os.path.dirname(os.path.dirname(os.path.dirname(d))))

def find_subject(sid):
    for d, owner in subject_dirs():
        if os.path.basename(d) == sid: return d, owner
    raise SystemExit(f'subject "{sid}" not found')

def load_subject(sdir):
    """Return (meta, sources, chapters, report): base chapters + additive patches, every item tagged with its source."""
    meta = rj(os.path.join(sdir, 'subject.json'))
    SRC = rj(os.path.join(sdir, 'sources.json'), {'sources': [], 'chapters': {}, 'patches': {}})
    chs = {}
    for f in sorted(glob.glob(os.path.join(sdir, 'chapters', 'ch*.json'))):
        c = rj(f); chs[c['id']] = c
        c.setdefault('src', SRC.get('chapters', {}).get(c['id']) or (SRC['sources'][0]['id'] if SRC.get('sources') else None))
    report = []
    for pf in sorted(glob.glob(os.path.join(sdir, 'patches', '*.json'))):
        P = rj(pf); psrc = SRC.get('patches', {}).get(os.path.basename(pf))
        for p in P['patches']:
            if psrc:
                for k in ('appendBlocks', 'appendExercises', 'appendFlashcards', 'appendPitfalls', 'appendDebug'):
                    for it in p.get(k, []): it.setdefault('src', psrc)
            c = chs.get(p['chapter'])
            if not c: report.append(f'ERROR {pf}: unknown chapter {p["chapter"]}'); continue
            if p.get('appendBlocks'):
                sec = next((s for s in c['sections'] if s['id'] == p.get('section')), None)
                if not sec: report.append(f'ERROR {pf}: unknown section {p.get("section")}'); continue
                sec['blocks'].extend(p['appendBlocks'])
            c['exercises'].extend(p.get('appendExercises', []))
            c['flashcards'].extend(p.get('appendFlashcards', []))
            c['pitfalls'].extend(p.get('appendPitfalls', []))
            c['debug'].extend(p.get('appendDebug', []))
            report.append(f'{os.path.basename(pf)} -> {p["chapter"]}/{p.get("section")}')
    return meta, SRC, [chs[k] for k in sorted(chs)], report

def content_hash(obj):
    return hashlib.sha256(json.dumps(obj, sort_keys=True, ensure_ascii=False).encode('utf-8')).hexdigest()[:16]

# ---------------- media (docs/VISUAL.md — noema.media/v1) ----------------
# Licences. noema-lite is a PERSONAL study app: any picture may be used as long as its source is recorded
# (url + credit + licence text). Openly licensed pictures ("open") can also be shared/published freely;
# the others ("restricted": NC, ND, all rights reserved, unknown) are marked so the app warns before a pack
# containing them is published or shared (docs/VISUAL.md §6).
OPEN_LICENSES = ['own', 'CC0', 'Public domain', 'PDM', 'CC BY', 'CC BY-SA', 'Apache-2.0', 'MIT', 'BSD', 'OGL', 'U.S. Government work', 'NASA', 'Etalab']
ALLOWED_LICENSES = OPEN_LICENSES          # backwards-compatible name
ORIGINS = {'drawn': 'drawn for noema-lite (svgkit / by hand)', 'plot': 'function graph generated by svgkit.Plot', 'source': 'extracted from the subject’s own sources', 'web': 'found online (source url + credit required)'}
def license_open(lic):
    import re
    l = (lic or '').strip().lower()
    toks = set(re.split(r'[\s\-_/]+', l))
    return any(l.startswith(a.lower()) for a in OPEN_LICENSES) and not toks & {'nc', 'nd', 'noncommercial', 'noderivatives'}
license_ok = license_open                 # backwards-compatible name

MIME = {'.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp'}

def image_size(path):
    """(w, h) of an svg/png/jpeg/webp file, or None — stdlib only."""
    import re, struct
    ext = os.path.splitext(path)[1].lower()
    data = open(path, 'rb').read()
    try:
        if ext == '.svg':
            t = data[:4000].decode('utf-8', 'ignore')
            m = re.search(r'viewBox\s*=\s*"\s*[-\d.]+[\s,]+[-\d.]+[\s,]+([\d.]+)[\s,]+([\d.]+)\s*"', t)
            if m: return float(m.group(1)), float(m.group(2))
            mw, mh = re.search(r'\bwidth\s*=\s*"([\d.]+)', t), re.search(r'\bheight\s*=\s*"([\d.]+)', t)
            return (float(mw.group(1)), float(mh.group(1))) if mw and mh else None
        if ext == '.png': return struct.unpack('>II', data[16:24])
        if ext == '.webp':
            if data[12:16] == b'VP8X': return 1 + int.from_bytes(data[24:27], 'little'), 1 + int.from_bytes(data[27:30], 'little')
            if data[12:16] == b'VP8L': b = data[21:25]; v = int.from_bytes(b, 'little'); return (v & 0x3FFF) + 1, ((v >> 14) & 0x3FFF) + 1
            if data[12:16] == b'VP8 ': return struct.unpack('<HH', data[26:30])[0] & 0x3FFF, struct.unpack('<HH', data[26:30])[1] & 0x3FFF
        if ext in ('.jpg', '.jpeg'):
            i = 2
            while i < len(data):
                if data[i] != 0xFF: i += 1; continue
                mk = data[i + 1]
                if mk in (0xC0, 0xC1, 0xC2): h, w = struct.unpack('>HH', data[i + 5:i + 9]); return w, h
                i += 2 + struct.unpack('>H', data[i + 2:i + 4])[0]
    except Exception: return None
    return None

def load_media(sdir, embed=True):
    """Return ({id: item}, report). Items carry mime, w, h and (embed=True) a data: URI."""
    import base64
    reg = rj(os.path.join(sdir, 'media', 'media.json'), {'format': 'noema.media/v1', 'items': []})
    out, report = {}, []
    if reg.get('format') != 'noema.media/v1': report.append('ERROR media.json: format must be "noema.media/v1"')
    for it in reg.get('items', []):
        mid = it.get('id', '?'); f = os.path.join(sdir, 'media', it.get('file', ''))
        if mid in out: report.append(f'ERROR media {mid}: duplicate id'); continue
        if it.get('fetch') == 'app' and not it.get('file'):
            # a web picture the noema-lite app downloads itself when the pack is imported (used when the
            # builder's sandbox has no internet, e.g. "Create with Claude" inside the app): url + size, no file
            bad = [k for k in ('url', 'retrieved', 'alt', 'credit', 'license') if not str(it.get(k, '')).strip()]
            if it.get('origin') != 'web': bad.append('origin "web"')
            if not (isinstance(it.get('w'), (int, float)) and isinstance(it.get('h'), (int, float)) and it['w'] > 0 and it['h'] > 0): bad.append('w and h (pixels)')
            if bad: report.append(f'ERROR media {mid}: a "fetch": "app" picture needs ' + ', '.join(bad)); continue
            if max(it['w'], it['h']) < 800 and not it.get('lowResOk'): report.append(f'ERROR media {mid}: {it["w"]:g}×{it["h"]:g} px is too small (≥ 800 px on the long side)')
            ext = os.path.splitext(it['url'].split('?')[0])[1].lower()
            item = dict(it, mime=it.get('mime') or MIME.get(ext, 'image/jpeg'), origin='web')
            if not license_open(it.get('license')): item['restricted'] = True
            out[mid] = item; continue
        if not os.path.isfile(f): report.append(f'ERROR media {mid}: file {it.get("file")} not found'); continue
        ext = os.path.splitext(f)[1].lower()
        if ext not in MIME: report.append(f'ERROR media {mid}: unsupported file type {ext}'); continue
        for k in ('alt', 'credit', 'license'):
            if not str(it.get(k, '')).strip(): report.append(f'ERROR media {mid}: missing {k}')
        size = os.path.getsize(f)
        if ext != '.svg' and size > 600_000: report.append(f'WARN media {mid}: {size // 1024} KB (keep rasters ≤ 600 KB: crop / JPEG quality 85)')
        wh = (it.get('w'), it.get('h')) if it.get('w') and it.get('h') else image_size(f)
        if not wh: report.append(f'ERROR media {mid}: cannot detect the image size — add "w" and "h"'); continue
        # provenance + quality (docs/VISUAL.md §6)
        origin = it.get('origin') or ('drawn' if ext == '.svg' else None)
        if origin not in ORIGINS: report.append(f'ERROR media {mid}: "origin" must be one of {sorted(ORIGINS)}')
        if origin == 'web':
            for k in ('url', 'retrieved'):
                if not str(it.get(k, '')).strip(): report.append(f'ERROR media {mid}: web picture needs "{k}" (always record where it came from)')
        restricted = not license_open(it.get('license')) and origin in ('web', 'source')
        if ext != '.svg' and max(wh) < 800 and not it.get('lowResOk'):
            report.append(f'ERROR media {mid}: {wh[0]:g}×{wh[1]:g} px is too small (≥ 800 px on the long side, or set "lowResOk": "why it is still sharp enough")')
        item = dict(it, mime=MIME[ext], w=wh[0], h=wh[1], origin=origin)
        if restricted: item['restricted'] = True        # personal use only → the app warns before sharing/publishing
        item.pop('file', None)
        raw = open(f, 'rb').read()
        item['sha'] = hashlib.sha256(raw).hexdigest()[:16]
        if embed: item['data'] = f'data:{MIME[ext]};base64,' + base64.b64encode(raw).decode('ascii')
        out[mid] = item
    return out, report

# ---------------- source files packaged with the pack (docs/SOURCES.md §3) ----------------
SOURCE_FILE_MAX = 50 * 1024 * 1024        # the app's and the cloud bucket's limit per file
def _mime(fn):
    import mimetypes
    ext = os.path.splitext(fn)[1].lower()
    extra = {'.md': 'text/markdown', '.epub': 'application/epub+zip', '.ipynb': 'application/x-ipynb+json', '.heic': 'image/heic', '.heif': 'image/heif', '.eml': 'message/rfc822',
             '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
             '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation', '.odt': 'application/vnd.oasis.opendocument.text', '.webp': 'image/webp'}
    return extra.get(ext) or mimetypes.guess_type(fn)[0] or 'application/octet-stream'

def pdf_page_count(path):
    """Number of pages of a PDF (pdfinfo, pypdf or PyMuPDF), or None."""
    import subprocess, re
    try:
        out = subprocess.run(['pdfinfo', path], capture_output=True, text=True, timeout=60).stdout
        m = re.search(r'^Pages:\s+(\d+)', out, re.M)
        if m: return int(m.group(1))
    except Exception: pass
    try:
        from pypdf import PdfReader; return len(PdfReader(path).pages)
    except Exception: pass
    try:
        try: import pymupdf as fitz
        except ImportError: import fitz
        return fitz.open(path).page_count
    except Exception: return None

def _first_page(txt):
    import re
    m = re.search(r'(?:σελ\.?|σσ\.|σ\.|pp?\.|pages?|S\.)\s*(\d{1,5})', str(txt or ''), re.I) or re.match(r'\s*(\d{1,5})\b', str(txt or ''))
    return int(m.group(1)) if m else None

def package_sources(sdir, sources, chapters, base_ids=()):
    """Check the original files of the sources and describe them for the pack.
    Every source with a local "file" (sources/<name>) must have that file in SDIR/sources/ (≤ 50 MB); every file in
    SDIR/sources/ must belong to a source (so nothing the learner gave is left out — a split PDF = one source per part).
    Returns (sources_json, files, errors, warnings); files = [(source_id, abs_path, 'sources/<name>')].
    base_ids: sources of the previous version (unpacked from a .json without files) — their file is already in the
    learner's account, so a missing file there is only a warning."""
    import copy, hashlib as H
    out = copy.deepcopy(sources or {'sources': [], 'chapters': {}, 'patches': {}})
    errs, warns, files = [], [], []
    sdir_src = os.path.join(sdir, 'sources')
    used_paths = set(); ids = set()
    cited = {}
    for c in chapters:
        for r in c.get('sources') or []:
            if isinstance(r, dict) and r.get('id'): cited.setdefault(r['id'], []).append((c['id'], r.get('pages', '')))
        if c.get('src'): cited.setdefault(c['src'], []).append((c['id'], ''))
    for s in out.get('sources', []):
        sid = s.get('id'); ids.add(sid)
        if not sid: errs.append('ERROR sources.json: a source without "id"'); continue
        f = str(s.get('file') or '').strip()
        if not f or f.startswith(('http://', 'https://')):
            for k in ('size', 'sha256', 'fileName', 'mime', 'pageCount'): s.pop(k, None)
            continue
        rel = f.replace('\\', '/').lstrip('./')
        if not rel.startswith('sources/') or '..' in rel.split('/'):
            if sid in base_ids:
                warns.append(f'WARN source {sid}: "file" {f} is kept from the previous version (the learner already has it)'); [s.pop(k, None) for k in ('size', 'sha256')]; continue
            errs.append(f'ERROR source {sid}: "file" must be "sources/<file name>" (the file inside {os.path.basename(sdir)}/sources/), not "{f}"'); continue
        p = os.path.join(sdir, *rel.split('/'))
        if not os.path.isfile(p):
            if sid in base_ids:
                warns.append(f'WARN source {sid}: {rel} is not in the folder — kept from the previous version (the learner already has it)')
                for k in ('size', 'sha256'): s.pop(k, None)
            else:
                errs.append(f'ERROR source {sid}: its file {rel} is missing — copy the original (or the split part) into {os.path.basename(sdir)}/sources/')
            continue
        size = os.path.getsize(p)
        if size > SOURCE_FILE_MAX: errs.append(f'ERROR source {sid}: {rel} is {size // 1048576} MB — the limit is 50 MB per file: split it with scripts/split_pdf.py and give each part its own source'); continue
        if size == 0: errs.append(f'ERROR source {sid}: {rel} is empty'); continue
        h = H.sha256()
        with open(p, 'rb') as fh:
            for chunk in iter(lambda: fh.read(1 << 20), b''): h.update(chunk)
        s['file'] = rel; s['fileName'] = s.get('fileName') or os.path.basename(rel); s['size'] = size; s['sha256'] = h.hexdigest(); s['mime'] = _mime(rel)
        used_paths.add(os.path.normcase(os.path.abspath(p))); files.append((sid, p, rel))
        if rel.lower().endswith('.pdf'):
            n = pdf_page_count(p)
            if n:
                s['pageCount'] = n
                first = int(s.get('firstPage') or 1)
                for ch, pg in cited.get(sid, []):
                    fp = _first_page(pg)
                    if fp is not None and not (first <= fp <= first + n - 1):
                        warns.append(f'WARN {ch}: cites {sid} "{pg}" but {rel} has pages {first}–{first + n - 1}' + (' (set "firstPage" on a split part: the page number your citations use for its first page)' if first == 1 else ''))
        if sid not in cited: warns.append(f'WARN source {sid}: no chapter uses it (add it to the chapters\' "sources")')
    if os.path.isdir(sdir_src):
        for root, _, fns in os.walk(sdir_src):
            for fn in fns:
                if fn.startswith('.'): continue
                p = os.path.normcase(os.path.abspath(os.path.join(root, fn)))
                if p not in used_paths:
                    errs.append(f'ERROR {os.path.relpath(os.path.join(root, fn), sdir)}: no source in sources.json points to this file — every file the learner gave (or each part of a split PDF) needs its own source with "file": "sources/{fn}"; remove files that are not sources (e.g. the unsplit original when you use its parts)')
    for ch, src in (out.get('chapters') or {}).items():
        if src not in ids: errs.append(f'ERROR sources.json: chapter {ch} → unknown source "{src}"')
    for c in chapters:
        for r in c.get('sources') or []:
            if isinstance(r, dict) and r.get('id') and r['id'] not in ids: errs.append(f'ERROR {c["id"]}: "sources" names unknown source "{r["id"]}"')
    return out, files, errs, warns

def write_bundle(path, pack, files):
    """The package the app imports: a zip with pack.json + sources/<file> for every packaged source file."""
    import zipfile
    os.makedirs(os.path.dirname(os.path.abspath(path)) or '.', exist_ok=True)
    tmp = path + '.tmp'
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as z:
        z.writestr('pack.json', json.dumps(pack, ensure_ascii=False, separators=(',', ':')))
        for sid, p, rel in files:
            # PDFs / pictures / media are already compressed: store them (fast, no size gain lost)
            comp = zipfile.ZIP_STORED if os.path.splitext(rel)[1].lower() in ('.pdf', '.png', '.jpg', '.jpeg', '.webp', '.zip', '.mp4', '.mp3', '.m4a', '.docx', '.pptx', '.xlsx', '.epub', '.heic') else zipfile.ZIP_DEFLATED
            z.write(p, rel, compress_type=comp)
    os.replace(tmp, path)
