"""Shared helpers for noema-lite tools (stdlib only — runs anywhere Python 3.8+ runs)."""
import json, os, glob, hashlib, datetime

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
LIB = os.path.join(ROOT, 'library')
ACC = os.path.join(ROOT, 'accounts')

def rj(p, default=None):
    if default is not None and not os.path.exists(p): return default
    with open(p, encoding='utf-8') as f: return json.load(f)

def wj(p, obj, compact=False):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tmp = p + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as f:
        if compact: json.dump(obj, f, ensure_ascii=False, separators=(',', ':'))
        else: json.dump(obj, f, ensure_ascii=False, indent=1)
    os.replace(tmp, p)

def wt(p, text):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    tmp = p + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as f: f.write(text)
    os.replace(tmp, p)

def now_iso(): return datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat()

def subject_dirs():
    """Yield (subject_dir, owner) for shared subjects and every account's private subjects."""
    for d in sorted(glob.glob(os.path.join(LIB, 'subjects', '*', 'subject.json'))):
        yield os.path.dirname(d), None
    for d in sorted(glob.glob(os.path.join(ACC, '*', 'packs', '*', 'subject.json'))):
        yield os.path.dirname(d), os.path.basename(os.path.dirname(os.path.dirname(os.path.dirname(d))))

def find_subject(sid):
    for d, owner in subject_dirs():
        if os.path.basename(d) == sid: return d, owner
    raise SystemExit(f'subject "{sid}" not found')

def load_subject(sdir):
    """Return (meta, sources, chapters, report): base chapters + additive patches, every item tagged with its source."""
    meta = rj(os.path.join(sdir, 'subject.json'))
    SRC = rj(os.path.join(sdir, 'sources.json'), {'sources': [], 'chapters': {}, 'patches': {}})
    chs = {}
    for f in sorted(glob.glob(os.path.join(sdir, 'chapters', 'ch*.json'))):
        c = rj(f); chs[c['id']] = c
        c.setdefault('src', SRC.get('chapters', {}).get(c['id']) or (SRC['sources'][0]['id'] if SRC.get('sources') else None))
    report = []
    for pf in sorted(glob.glob(os.path.join(sdir, 'patches', '*.json'))):
        P = rj(pf); psrc = SRC.get('patches', {}).get(os.path.basename(pf))
        for p in P['patches']:
            if psrc:
                for k in ('appendBlocks', 'appendExercises', 'appendFlashcards', 'appendPitfalls', 'appendDebug'):
                    for it in p.get(k, []): it.setdefault('src', psrc)
            c = chs.get(p['chapter'])
            if not c: report.append(f'ERROR {pf}: unknown chapter {p["chapter"]}'); continue
            if p.get('appendBlocks'):
                sec = next((s for s in c['sections'] if s['id'] == p.get('section')), None)
                if not sec: report.append(f'ERROR {pf}: unknown section {p.get("section")}'); continue
                sec['blocks'].extend(p['appendBlocks'])
            c['exercises'].extend(p.get('appendExercises', []))
            c['flashcards'].extend(p.get('appendFlashcards', []))
            c['pitfalls'].extend(p.get('appendPitfalls', []))
            c['debug'].extend(p.get('appendDebug', []))
            report.append(f'{os.path.basename(pf)} -> {p["chapter"]}/{p.get("section")}')
    return meta, SRC, [chs[k] for k in sorted(chs)], report

def content_hash(obj):
    return hashlib.sha256(json.dumps(obj, sort_keys=True, ensure_ascii=False).encode('utf-8')).hexdigest()[:16]

# ---------------- media (docs/VISUAL.md — noema.media/v1) ----------------
# Licences under which a picture from the web may be reused (with credit). Anything else: draw it yourself instead.
ALLOWED_LICENSES = ['own', 'CC0', 'Public domain', 'PDM', 'CC BY', 'CC BY-SA', 'Apache-2.0', 'MIT', 'BSD', 'OGL', 'U.S. Government work', 'NASA', 'Etalab']
ORIGINS = {'drawn': 'drawn for noema-lite (svgkit / by hand)', 'plot': 'function graph generated by svgkit.Plot', 'source': 'extracted from the subject’s own sources', 'web': 'found online (open licence, with url/author)'}
def license_ok(lic):
    l = (lic or '').strip().lower()
    import re
    toks = set(re.split(r'[\s\-_/]+', l))
    return any(l.startswith(a.lower()) for a in ALLOWED_LICENSES) and not toks & {'nc', 'nd', 'noncommercial', 'noderivatives'}

MIME = {'.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp'}

def image_size(path):
    """(w, h) of an svg/png/jpeg/webp file, or None — stdlib only."""
    import re, struct
    ext = os.path.splitext(path)[1].lower()
    data = open(path, 'rb').read()
    try:
        if ext == '.svg':
            t = data[:4000].decode('utf-8', 'ignore')
            m = re.search(r'viewBox\s*=\s*"\s*[-\d.]+[\s,]+[-\d.]+[\s,]+([\d.]+)[\s,]+([\d.]+)\s*"', t)
            if m: return float(m.group(1)), float(m.group(2))
            mw, mh = re.search(r'\bwidth\s*=\s*"([\d.]+)', t), re.search(r'\bheight\s*=\s*"([\d.]+)', t)
            return (float(mw.group(1)), float(mh.group(1))) if mw and mh else None
        if ext == '.png': return struct.unpack('>II', data[16:24])
        if ext == '.webp':
            if data[12:16] == b'VP8X': return 1 + int.from_bytes(data[24:27], 'little'), 1 + int.from_bytes(data[27:30], 'little')
            if data[12:16] == b'VP8L': b = data[21:25]; v = int.from_bytes(b, 'little'); return (v & 0x3FFF) + 1, ((v >> 14) & 0x3FFF) + 1
            if data[12:16] == b'VP8 ': return struct.unpack('<HH', data[26:30])[0] & 0x3FFF, struct.unpack('<HH', data[26:30])[1] & 0x3FFF
        if ext in ('.jpg', '.jpeg'):
            i = 2
            while i < len(data):
                if data[i] != 0xFF: i += 1; continue
                mk = data[i + 1]
                if mk in (0xC0, 0xC1, 0xC2): h, w = struct.unpack('>HH', data[i + 5:i + 9]); return w, h
                i += 2 + struct.unpack('>H', data[i + 2:i + 4])[0]
    except Exception: return None
    return None

def load_media(sdir, embed=True):
    """Return ({id: item}, report). Items carry mime, w, h and (embed=True) a data: URI."""
    import base64
    reg = rj(os.path.join(sdir, 'media', 'media.json'), {'format': 'noema.media/v1', 'items': []})
    out, report = {}, []
    if reg.get('format') != 'noema.media/v1': report.append('ERROR media.json: format must be "noema.media/v1"')
    for it in reg.get('items', []):
        mid = it.get('id', '?'); f = os.path.join(sdir, 'media', it.get('file', ''))
        if mid in out: report.append(f'ERROR media {mid}: duplicate id'); continue
        if not os.path.isfile(f): report.append(f'ERROR media {mid}: file {it.get("file")} not found'); continue
        ext = os.path.splitext(f)[1].lower()
        if ext not in MIME: report.append(f'ERROR media {mid}: unsupported file type {ext}'); continue
        for k in ('alt', 'credit', 'license'):
            if not str(it.get(k, '')).strip(): report.append(f'ERROR media {mid}: missing {k}')
        size = os.path.getsize(f)
        if ext != '.svg' and size > 600_000: report.append(f'WARN media {mid}: {size // 1024} KB (keep rasters ≤ 600 KB: crop / JPEG quality 85)')
        wh = (it.get('w'), it.get('h')) if it.get('w') and it.get('h') else image_size(f)
        if not wh: report.append(f'ERROR media {mid}: cannot detect the image size — add "w" and "h"'); continue
        # provenance + quality (docs/VISUAL.md §6)
        origin = it.get('origin') or ('drawn' if ext == '.svg' else None)
        if origin not in ORIGINS: report.append(f'ERROR media {mid}: "origin" must be one of {sorted(ORIGINS)}')
        if origin == 'web':
            for k in ('url', 'retrieved'):
                if not str(it.get(k, '')).strip(): report.append(f'ERROR media {mid}: web picture needs "{k}"')
            if not license_ok(it.get('license')): report.append(f'ERROR media {mid}: licence "{it.get("license")}" is not reusable (allowed: {", ".join(ALLOWED_LICENSES)}; no NC/ND)')
        if ext != '.svg' and max(wh) < 800 and not it.get('lowResOk'):
            report.append(f'ERROR media {mid}: {wh[0]:g}×{wh[1]:g} px is too small (≥ 800 px on the long side, or set "lowResOk": "why it is still sharp enough")')
        item = dict(it, mime=MIME[ext], w=wh[0], h=wh[1], origin=origin)
        item.pop('file', None)
        raw = open(f, 'rb').read()
        item['sha'] = hashlib.sha256(raw).hexdigest()[:16]
        if embed: item['data'] = f'data:{MIME[ext]};base64,' + base64.b64encode(raw).decode('ascii')
        out[mid] = item
    return out, report
